AllDialogue.VoiceLines["Alecto"] = {
	["0002"] = [=[Ah, hah hah, hohohohohhh. Finally. I've been waiting for this! Really.]=],
	["0003"] = [=[...So sick of, you know, doing my regular job, uninterrupted. Not having to clean up Meg's messes!]=],
	["0004"] = [=[Anyway. I always wanted to kill a god. You'll have to do.]=],
	["0005"] = [=[You're no god! You're nothing but a piece of trash. Born into all of this. And you don't even want it!]=],
	["0006"] = [=[Tsch. Well. You want to know what I want? Here, I'll show you.]=],
	["0007"] = [=[You know what I like about you? The way you bleed. Mmm.]=],
	["0008"] = [=[Never met a god that bleeds like you. Red. Like a worthless mortal. Come on! Let's bleed you dry.]=],
	["0009"] = [=[Let's get to work, redblood, what do you say? Me, I say you've kept this girl waiting long enough.]=],
	["0010"] = [=[Oh, hoho, you're funny. But you'll break. They always do.]=],
	["0011"] = [=[I have got to admit, you are really frustrating, you know, redblood? What is it going to take to make you scream, hm?]=],
	["0012"] = [=[Ehh, we'll find out. I've got plenty of ideas left I've been meaning to try.]=],
	["0013"] = [=[You know something, redblood? In retrospect, I should have known this wasn't going to be a quick job.]=],
	["0014"] = [=[Normally when I'm on the job, they grovel, then they scream. They shut up eventually, but not you. At least, not yet.]=],
	["0015"] = [=[Oh hey, redblood! You're back for more. I like that stubborn stupidness about you, honestly. If only I could keep you alive even longer this time.]=],
	["0016"] = [=[Haven't decided how just yet. This girl likes a little spontaneity.]=],
	["0017"] = [=[Huh! Normally my marks don't make a habit of seeking me out again after I'm through with them.]=],
	["0018"] = [=[Ugh, I do so hate to let you down like this, redblood. But you're just not my type. Maybe I'll finally get it through your head this time.]=],
	["0019"] = [=[Huh! You really must like pain an awful lot, redblood. Or maybe it's just me.]=],
	["0020"] = [=[Did you just--? Don't you ever compare yourself to me again, you trash. You want more pain, I'm happy to oblige.]=],
	["0021"] = [=[Know something, redblood? Try as I might, I still have not forgiven you for beating me last time. Call it a crippling character flaw, I don't know...]=],
	["0022"] = [=[You think we're making progress? Here? Ah, hah, ha-hah, ha-hah, ha-hah, why you piece of trash! I'll show you progress.]=],
	["0023"] = [=[Redblood, I'm getting awful sick of seeing your smug face, time, after time, after time.]=],
	["0024"] = [=[You see? That is exactly what I mean. To think that Megaera had to put up with you for, I don't know how long.]=],
	["0025"] = [=[Damn you for this, redblood. You're making me look bad, you know? Making me feel bad.]=],
	["0026"] = [=[Ah-hahah-hahaha, hahah, you do know what happens when you make me feel bad, don't you...?]=],
	["0027"] = [=[I'm going to enjoy this, redblood.]=],
	["0028"] = [=[Just when I was beginning to feel bored.]=],
	["0029"] = [=[I'm going to tear you limb from limb, redblood.]=],
	["0030"] = [=[The Fates must want to spill your blood as much as I do.]=],
	["0031"] = [=[Time to die, again, redblood. Let's get to killing you.]=],
	["0032"] = [=[This job never gets old, redblood, I can assure you that.]=],
	["0033"] = [=[Well if it isn't the god of trash himself. Come die.]=],
	["0034"] = [=[Good, I was getting real tired waiting around to kill you.]=],
	["0035"] = [=[Aww, you came back all this way! I'm flattered, redblood.]=],
	["0036"] = [=[Got some kind of deathwish, don't you. Fine.]=],
	["0041"] = [=[Oh, thank the Fates I get to deal with you this time.]=],
	["0042"] = [=[Let's see what you can do, redblood. Come on!]=],
	["0043"] = [=[Well! Look who's back. The god of trash, himself.]=],
	["0044"] = [=[Get ready for a bunch of pain and suffering, trash god.]=],
	["0045"] = [=[Whoa, whoa, whoa, hold it right there, redblood.]=],
	["0046"] = [=[You think just 'cause you got through Megaera, you'll get through me?]=],
	["0047"] = [=[Your daddy never should have given Megaera this job.]=],
	["0048"] = [=[Megaera couldn't make it, redblood, so it's me and you.]=],
	["0049"] = [=[Hah! It's Megaera's hot mess. Let's clean you up.]=],
	["0050"] = [=[You got Tisiphone, so what. Now I'll get you.]=],
	["0051"] = [=[You mess with Tis, redblood, you mess with me, get it?]=],
	["0052"] = [=[Tisiphone's been having problems with you, huh. Let's see if I can help.]=],
	["0053"] = [=[Nobody messes with Tisiphone but me, redblood.]=],
	["0054"] = [=[Ohh, there he is, sisters. It's time to get to work.]=],
	["0055"] = [=[You ready, Megaera? Tisiphone? Let's go.]=],
	["0056"] = [=[Let's tear him into shreds, sisters, come on!]=],
	["0057"] = [=[Hey, check it out, sisters, he's back. You ready?]=],
	["0058"] = [=[He's come crawling back again, sisters. Let's get him, then.]=],
	["0059"] = [=[You ready, Sis? This redblood's nothing to the both of us.]=],
	["0060"] = [=[Check it out, Sis! The god of trash is here. Let's get to work.]=],
	["0061"] = [=[Well, Sis, what do you say we get started on him?]=],
	["0062"] = [=[There he is, Sis! I'm ready if you're ready.]=],
	["0063"] = [=[I'll just keep killing you, redblood. Not that I mind!]=],
	["0064"] = [=[What are we going to do with you this time, now, hm?]=],
	["0065"] = [=[I'm impressed, redblood. You really never learn.]=],
	["0066"] = [=[Turns out, killing the god of trash never gets old.]=],
	["0067"] = [=[How would you like to die this time, redblood? Here, let me guess.]=],
	["0068"] = [=[You just don't get it, do you? Though I bet I can make you learn.]=],
	["0069"] = [=[I'm getting real sick of you, trash god. Come on!]=],
	["0070"] = [=[Bad news for you, redblood. I like dying.]=],
	["0071"] = [=[Come on, redblood, let's see you kill me again!]=],
	["0072"] = [=[You're stuck with me forever, trash. Remember that.]=],
	["0073"] = [=[I'm really starting to hate you. You know that, redblood?]=],
	["0074"] = [=[Why if it isn't the god of trash himself. I'm so honored.]=],
	["0075"] = [=[Good news for you, I'm in a real bad mood right now.]=],
	["0076"] = [=[Been looking forward to this chance to get you back, redblood.]=],
	["0077"] = [=[Heard you were in the area, and thought I'd take another stab at killing you.]=],
	["0078"] = [=[Redblood, I really don't appreciate what happened here last time.]=],
	["0166?"] = [=[You ready, Megaera? Tisiphone? Let's go.]=],
	["0266"] = [=[Megaera, bleed him!]=],
	["0295"] = [=[Megaera, Tis, you ready?]=],
	["0313"] = [=[Ahh, look at you, redblood. You're practically already dead! Now that's no fun at all.]=],
	["0314"] = [=[Oh, that's all right, no hard feelings at all! You just be sure to get in better health before next I get to kill you, hm?]=],
	["0315"] = [=[You know I smelled your blood from three chambers away? Hope you saved some of it for me.]=],
	["0316"] = [=[Do I look like someone who doesn't mind, trash god? I'll take your blood, however much you've got.]=],
	["0317"] = [=[What's the matter, redblood? You look a little paler than usual. Been bleeding much, having to get this far?]=],
	["0318"] = [=[Oh whew, that's a relief all right! I was so worried that I wasn't going to be the one to kill you this time.]=],
	["0319"] = [=[Huh, it's the god of trash, come once again to filthy up this place! You're getting real predictable, you know.]=],
	["0320"] = [=[Don't want to hear it from you, trash! Just want to see you bleed. Now you come here!]=],
	["0321"] = [=[Hey, redblood. I have done a lot of thinking, and I've come to the conclusion that I want you never to speak to me again. Ever. Got that?]=],
	["0322"] = [=[You'll die! There's no use standing here flapping our gums when we could cut to killing one another right away. Come on!]=],
	["0323"] = [=[Ugh, would you just look at him! That smug look, that posture, everything! Please tell me you're not going soft for this trash-god, Sister.]=],
	["0324"] = [=[You know, fair point, there, Sister! Very nicely said. Let's kill him, now!]=],
	["0325"] = [=[Look at this awful piece of trash, come here again to bleed all over our nice shiny floor. Ready to fight my lovely sister, there, redblood?]=],
	["0326"] = [=[The both of you disgust me, Meg, you know that? Get it together and kill him this time, damn you!]=],
	["0327"] = [=[You must have gone and signed a Pact! Isn't that right, redblood? Tell me right now.]=],
	["0328"] = [=[I like working alone! And you don't see me doing that, right now, do you? So I would say it's my business, all right. Along with killing you!]=],
	["0329"] = [=[Whew, I thought I'd never get some quiet time again, you know, redblood? That damned Pact you stupidly agreed to, making me work with my sisters again. I'll get you for that!]=],
	["0330"] = [=[Oh, that's rich! How smart of you, you're smart! Know what? I'll get you for that, too.]=],
	["0331"] = [=[You're looking pretty beat already, there, redblood. So let's finish you off.]=],
	["0332"] = [=[Next time, don't you go losing so much blood before you get here, trash! I like to take it out of you myself.]=],
	["0333"] = [=[Been waiting here to beat you to a bloody pulp, redblood!]=],
	["0334"] = [=[Don't even open that damn mouth of yours, redblood. Except to scream.]=],
	["0335"] = [=[You must like pain, or something, don't you, there, redblood?]=],
	["0336"] = [=[Somebody's dying soon, redblood! Ohh, I can't wait.]=],
	["0337"] = [=[Come give me everything you've got, trash god!]=],
	["0338"] = [=[Let's see what you're made of, trash god! Come on!]=],
	["0339"] = [=[Looks like my prayers to the god of trash have finally been answered, huh?!]=],
	["0340"] = [=[What's the matter, there, redblood? Gone awful quiet! Did I hurt your feelings, huh?]=],
	["0341"] = [=[Ohh, I'm going to bleed you till you're dry.]=],
	["0342"] = [=[You want to mess with me again, redblood?! Well then, come on!]=],
	["0343"] = [=[How is it possible I am so sick of you, but never sick of killing you, redblood?]=],
	["0344"] = [=[Step on it, redblood! I've got lots of other trash to whip, you know!]=],
	["0345"] = [=[You might get through me, trash god, but I'm going to spill your blood before you do!]=],
	["0346"] = [=[You want through that door back there, it's going to cost you blood!]=],
	["0347"] = [=[Megaera's not just weak, she's got bad taste to match.]=],
	["0348"] = [=[Oh good, I was just itching for a live one, here, trash god.]=],
	["0349"] = [=[Live or die, your daddy doesn't care, redblood!]=],
	["0350"] = [=[Good thing your daddy hates you, or I wouldn't have the pleasure here, redblood!]=],
	["0351"] = [=[I'm real sick of waiting here, so how about we make this real quick, redblood!]=],
	["0352"] = [=[Nothing like nice, fresh blood to warm things up in here, I always say!]=],
	["0353"] = [=[When I heard you were coming through, redblood, I told my sisters I would see you here.]=],
	["0354"] = [=[Ohh, we are going to enjoy this, here, redblood!]=],
	["0355"] = [=[All right, sisters! Don't screw this up for me!]=],
	["0356"] = [=[I'm taking point against this trash, sisters. You back me up.]=],
	["0357"] = [=[All three of us against this trash, sisters? All right!]=],
	["0358"] = [=[The three Furies up against the trash god! What a fight!]=],
	["0359"] = [=[Oh, hohohohoho, look at him, sisters! Don't you just want to whip him all to shreds?!]=],
	["0360"] = [=[Much as I love chatting with you, Meg, Tisiphone... our prey is here.]=],
	["0361"] = [=[All right, Sister! Let's rip him all to shreds!]=],
	["0362"] = [=[You ready for him, Sister? I most definitely am!]=],
	["0363"] = [=[You're never getting through the both of us without losing a lot of blood, trash god.]=],
	["0364"] = [=[My sis and I, we're going to tear you limb from limb, redblood!]=],
	["0365"] = [=[Think you can scoot right past the both of us, trash god?!]=],
	["0366"] = [=[All right, Sis! You just back me up against this trash!]=],
	["0367"] = [=[Long as I slow you down, redblood, I've done my job.]=],
	["0368"] = [=[Heard you were in the area and volunteered for this, trash god.]=],
	["0369"] = [=[Time to spill it for me once again, redblood.]=],
	["0370"] = [=[I'll send you screaming home to daddy, now come on!!]=],
	["0371"] = [=[I've got a lot to be thankful for, you know, redblood? Your daddy could have shut you in the lowest pits, and then we never would have met!]=],
	["0372"] = [=[I don't know! I mean, before we met, I flayed all sorts of other trash down here! But lately I've been keeping them waiting, because of you.]=],
	["0373"] = [=[Good job, redblood! You made it all this way! But, I have got to send you back to daddy, now. Nothing personal!]=],
	["0374"] = [=[Oh, you know, I'd rather have my eyes put out, but thanks for offering! Now, time to head on home.]=],
	["0375"] = [=[You know, redblood, my appointments usually don't come to me, much less again and again! Think I'm here to show you a good time, huh?!]=],
	["0376"] = [=[Whaa?! You think dealing with me beats dealing with that weakling? Graaaah!]=],
	["0377"] = [=[How many times is it going to take, redblood? How many?! Tell me! How can you stand running into me like this, over and over?]=],
	["0378"] = [=[I'll give you one thing... I like it when my prey bites back. Come on, let's see some blood again.]=],
	["0379"] = [=[Tisiphone's started to say the strangest things, lately, redblood. You wouldn't happen to know anything about that, would you?]=],
	["0380"] = [=[Stay out of her head!! You really think she's got something to learn from you? Learn to shut up from her!]=],
	["0381"] = [=[Eugh, still can't believe Megaera got mixed up with you, redblood. For all her weakness, I always thought at least she took her job here seriously. Eh, live and learn!]=],
	["0382"] = [=[Ohh, you might get mad? Defend Megaera's honor, since she's far too weak to do it her damn self? You think she's so pure! Hahaha! You're disgusting! Both of you.]=],
	["0441"] = [=[Heard rumblings about some news back at your daddy's House, redblood. So his illustrious abducted Queen, she's come back home?!]=],
	["0442"] = [=[I don't answer to her! She can come and go as she wants for all I care. But you want to know who can't?! Yeah, you.]=],
	["0443"] = [=[Heard you had a real bash down in your daddy's House, redblood. So sorry I couldn't make it. Next time, though, all right?]=],
	["0444"] = [=[Hohoho, I'm sure you did. But, you know, work comes first! So let's get busy.]=],
	["0445"] = [=[I got to ask, how come you keep on showing up, redblood? I thought you would have had enough beatings by now.]=],
	["0446"] = [=[You call this a good habit, huh? Maybe for me, it is. Well, come here all you like, and I will be here waiting, every single time! About once every three times, anyway.]=],
	["0037"] = [=[I wish it didn't have to be this way.]=],
	["0038"] = [=[Why must we always have to fight.]=],
	["0039"] = [=[It's time we had one of our little fights.]=],
	["0040"] = [=[I so was hoping you'd show up just now.]=],
	["0079"] = [=[Take this!]=],
	["0080"] = [=[Nraaugh!]=],
	["0081"] = [=[Pain.]=],
	["0082"] = [=[Try this!]=],
	["0083"] = [=[Catch this!]=],
	["0084"] = [=[Die already!]=],
	["0085"] = [=[Eat this!]=],
	["0086"] = [=[Here!]=],
	["0087"] = [=[Die!]=],
	["0088"] = [=[Kill!]=],
	["0089"] = [=[Suffer!]=],
	["0090"] = [=[Catch!]=],
	["0091"] = [=[Bleed!]=],
	["0092"] = [=[Here you go!]=],
	["0093"] = [=[I said die!]=],
	["0094"] = [=[Catch, redblood!]=],
	["0095"] = [=[How's this!]=],
	["0096"] = [=[Run.]=],
	["0097"] = [=[Run!]=],
	["0098"] = [=[You run!]=],
	["0099"] = [=[Pitiful.]=],
	["0100"] = [=[I'll kill you!]=],
	["0101"] = [=[Enough!]=],
	["0102"] = [=[Run for it.]=],
	["0103"] = [=[No escape.]=],
	["0104"] = [=[Hold still.]=],
	["0105"] = [=[You'll get yours.]=],
	["0106"] = [=[You better run.]=],
	["0107"] = [=[Hold still!]=],
	["0108"] = [=[Look out below.]=],
	["0109"] = [=[I'll get you.]=],
	["0110"] = [=[Pain...]=],
	["0111"] = [=[Hold it...]=],
	["0112"] = [=[Right here.]=],
	["0113"] = [=[Got you.]=],
	["0114"] = [=[Have another.]=],
	["0115"] = [=[Ready?]=],
	["0116"] = [=[Dodge this.]=],
	["0117"] = [=[Come closer.]=],
	["0118"] = [=[Don't move.]=],
	["0119"] = [=[Remember this?]=],
	["0120"] = [=[I'll make you hurt.]=],
	["0121"] = [=[Still standing huh.]=],
	["0122"] = [=[Die already.]=],
	["0123"] = [=[Still kicking?]=],
	["0124"] = [=[Still kicking are you.]=],
	["0125"] = [=[Still alive huh.]=],
	["0126"] = [=[I said die!]=],
	["0127"] = [=[Ooh, you're hurt.]=],
	["0128"] = [=[I'm going to kill you.]=],
	["0129"] = [=[I'll kill you yet.]=],
	["0130"] = [=[Aw, you're hurt.]=],
	["0131"] = [=[Not finished? Fine.]=],
	["0132"] = [=[You're as good as dead.]=],
	["0133"] = [=[Nice trick.]=],
	["0134"] = [=[Give up.]=],
	["0135"] = [=[You're dead.]=],
	["0136"] = [=[You're mine.]=],
	["0137"] = [=[You won't last.]=],
	["0138"] = [=[Got you that time.]=],
	["0139"] = [=[I bet that hurt.]=],
	["0140"] = [=[For last time.]=],
	["0141"] = [=[Hah!]=],
	["0142"] = [=[I'll get you yet.]=],
	["0143"] = [=[Hurts, doesn't it?]=],
	["0144"] = [=[Interesting...!]=],
	["0145"] = [=[Oho, hoh...!]=],
	["0146"] = [=[Angry now?]=],
	["0147"] = [=[Guess I hit a nerve.]=],
	["0148"] = [=[What's the matter?]=],
	["0149"] = [=[So...!]=],
	["0150"] = [=[So...]=],
	["0151"] = [=[What the--]=],
	["0152"] = [=[What the?]=],
	["0153"] = [=[Huh?]=],
	["0154"] = [=[Whoa.]=],
	["0155"] = [=[Easy, redblood.]=],
	["0156"] = [=[Ooh, you're mad!]=],
	["0157"] = [=[Relax, redblood.]=],
	["0158"] = [=[Aw, did that hurt?]=],
	["0159"] = [=[How was that?]=],
	["0160"] = [=[That was nothing.]=],
	["0161"] = [=[You're bleeding.]=],
	["0162"] = [=[Remember that.]=],
	["0163"] = [=[I'll make you scream.]=],
	["0164"] = [=[I'll hurt you worse than that.]=],
	["0165"] = [=[I feel your pain.]=],
	["0166"] = [=[That's it!]=],
	["0167"] = [=[My turn.]=],
	["0168"] = [=[That does it!]=],
	["0169"] = [=[Now you've done it.]=],
	["0170"] = [=[Graahhh!]=],
	["0171"] = [=[Rrryaah!]=],
	["0172"] = [=[Raaahh!]=],
	["0173"] = [=[Enough of this!]=],
	["0174"] = [=[Now!!]=],
	["0175"] = [=[Why, you!]=],
	["0176"] = [=[Enough!]=],
	["0177"] = [=[Whew.]=],
	["0178"] = [=[Whew!]=],
	["0179"] = [=[Nrrgghh...]=],
	["0180"] = [=[Mmph.]=],
	["0181"] = [=[Tsch.]=],
	["0182"] = [=[Brrr.]=],
	["0183"] = [=[Yeuggh.]=],
	["0184"] = [=[Urgh.]=],
	["0185"] = [=[Hrrr.]=],
	["0186"] = [=[T'ha, hah.]=],
	["0187"] = [=[You trash.]=],
	["0188"] = [=[Piece of trash.]=],
	["0189"] = [=[Tsch.]=],
	["0190"] = [=[Tsch, heh.]=],
	["0191"] = [=[Huh.]=],
	["0192"] = [=[Pff.]=],
	["0193"] = [=[You little.]=],
	["0194"] = [=[Really.]=],
	["0195"] = [=[Really?]=],
	["0196"] = [=[Damn.]=],
	["0197"] = [=[Damn it.]=],
	["0198"] = [=[Felt that.]=],
	["0199"] = [=[Ow.]=],
	["0200"] = [=[Not bad.]=],
	["0201"] = [=[How dare you.]=],
	["0202"] = [=[Urgh no.]=],
	["0203"] = [=[Augh damn!]=],
	["0204"] = [=[Ungh, you!]=],
	["0205"] = [=[Pfah!]=],
	["0206"] = [=[Gah!]=],
	["0207"] = [=[I don't think so.]=],
	["0208"] = [=[Try harder!]=],
	["0209"] = [=[Weak.]=],
	["0210"] = [=[Not a chance.]=],
	["0211"] = [=[No way.]=],
	["0212"] = [=[Nice try.]=],
	["0213"] = [=[Pshh.]=],
	["0214"] = [=[Really?]=],
	["0215"] = [=[Get out of here, redblood.]=],
	["0216"] = [=[See you next time, you trash.]=],
	["0217"] = [=[You're just like Megaera.]=],
	["0218"] = [=[I told you what was going to happen.]=],
	["0219"] = [=[Go on now back to daddy.]=],
	["0220"] = [=[Bye now, see you next time!]=],
	["0221"] = [=[Aw, we were just getting started.]=],
	["0222"] = [=[Right down the drain with you.]=],
	["0223"] = [=[Aw, over so soon?]=],
	["0224"] = [=[Another piece of trash goes down the drain.]=],
	["0225"] = [=[Tell Daddy I said hi.]=],
	["0226"] = [=[Finally.]=],
	["0227"] = [=[All right, all right, that's enough.]=],
	["0228"] = [=[Satisfied? I am.]=],
	["0229"] = [=[<Laughter>]=],
	["0230"] = [=[<Laughter>]=],
	["0231"] = [=[<Laughter>]=],
	["0232"] = [=[Come back again sometime!]=],
	["0233"] = [=[Until the next one, redblood.]=],
	["0234"] = [=[That never gets old, redblood.]=],
	["0235"] = [=[You know, I can get used to this!]=],
	["0236"] = [=[You don't have what it takes, redblood.]=],
	["0237"] = [=[Try not to waste my time again, hm?]=],
	["0238"] = [=[Finally, whew.]=],
	["0239"] = [=[Was just a matter of time I guess.]=],
	["0240"] = [=[We Fury Sisters do like our revenge.]=],
	["0241"] = [=[About damn time I got my way with you.]=],
	["0242"] = [=[You better not be going easy on me, redblood.]=],
	["0243"] = [=[That was a sloppy fight even for you, redblood.]=],
	["0244"] = [=[No way...!]=],
	["0245"] = [=[Damn, I--!]=],
	["0246"] = [=[How...!]=],
	["0247"] = [=[How...?!]=],
	["0248"] = [=[What...?!]=],
	["0249"] = [=[Gaah!]=],
	["0250"] = [=[I can't--!]=],
	["0251"] = [=[Again?!]=],
	["0252"] = [=[Ahh, why--!]=],
	["0253"] = [=[Why, you--!]=],
	["0254"] = [=[Ungh, damn...]=],
	["0255"] = [=[Damn you...]=],
	["0256"] = [=[Argh, how--!]=],
	["0257"] = [=[Megaera!]=],
	["0258"] = [=[Megaera...!]=],
	["0259"] = [=[Here, Megaera!]=],
	["0260"] = [=[Here, Megaera...!]=],
	["0261"] = [=[Megaera, now!]=],
	["0262"] = [=[Megaera, now!!]=],
	["0263"] = [=[Now, Megaera!]=],
	["0264"] = [=[Now, Megaera!!]=],
	["0265"] = [=[Megaera, get him!]=],
	["0267"] = [=[Megaera!!]=],
	["0268"] = [=[Damn it, Megaera.]=],
	["0269"] = [=[Megaera...]=],
	["0270"] = [=[Ready, Megaera.]=],
	["0271"] = [=[Ready, Sister!]=],
	["0272"] = [=[Ready, Sis!]=],
	["0273"] = [=[Tisiphone!]=],
	["0274"] = [=[Tisiphone...!]=],
	["0275"] = [=[Here, Tis!]=],
	["0276"] = [=[Here, Tis...!]=],
	["0277"] = [=[Tis, now!]=],
	["0278"] = [=[Tisiphone, now!!]=],
	["0279"] = [=[Now, Tis!]=],
	["0280"] = [=[Now, Tis!!]=],
	["0281"] = [=[Tisiphone, kill him!]=],
	["0282"] = [=[Tisiphone, kill!]=],
	["0283"] = [=[Tisiphone!!]=],
	["0284"] = [=[Tis, no...]=],
	["0285"] = [=[Tisiphone...]=],
	["0286"] = [=[Ready, Tis.]=],
	["0287"] = [=[I'm ready, Sister.]=],
	["0288"] = [=[I'm ready, Sis.]=],
	["0289"] = [=[Let's go, sisters!]=],
	["0290"] = [=[Now, sisters!]=],
	["0291"] = [=[Ready, sisters.]=],
	["0292"] = [=[Ready, sisters!]=],
	["0293"] = [=[Ready, sisters?]=],
	["0294"] = [=[Megaera, Tisiphone, now!!]=],
	["0296"] = [=[Erinyes, ready.]=],
	["0297"] = [=[Guess it's all up to me.]=],
	["0298"] = [=[I'll handle this myself.]=],
	["0299"] = [=[We are the Furies!!]=],
	["0300"] = [=[Now!]=],
	["0301"] = [=[Attack!]=],
	["0302"] = [=[Kill!]=],
	["0303"] = [=[We got him.]=],
	["0304"] = [=[We are the Furies.]=],
	["0305"] = [=[I guess we're finished here.]=],
	["0306"] = [=[He never stood a chance.]=],
	["0307"] = [=[<Laughter>]=],
	["0308"] = [=[<Laughter>]=],
	["0309"] = [=[<Laughter>]=],
	["0310"] = [=[<Laughter>]=],
	["0311"] = [=[<Laughter>]=],
	["0312"] = [=[<Laughter>]=],
	["0383"] = [=[Redblood!]=],
	["0384"] = [=[Finally.]=],
	["0385"] = [=[Oh, finally.]=],
	["0386"] = [=[You...!]=],
	["0387"] = [=[Pff.]=],
	["0388"] = [=[Nrrggh....]=],
	["0389"] = [=[Good...]=],
	["0390"] = [=[Well!]=],
	["0391"] = [=[Well, well!]=],
	["0392"] = [=[Oh, good.]=],
	["0393"] = [=[Oh...]=],
	["0394"] = [=[Trash god...]=],
	["0395"] = [=[There you are.]=],
	["0396"] = [=[Hohohoho.]=],
	["0397"] = [=[Stay there.]=],
	["0398"] = [=[Here!]=],
	["0399"] = [=[Why, you!]=],
	["0400"] = [=[Have this!]=],
	["0401"] = [=[Ready?!]=],
	["0402"] = [=[Want this?!]=],
	["0403"] = [=[You'll die!]=],
	["0404"] = [=[T'hah!]=],
	["0405"] = [=[Nrah, haha!]=],
	["0406"] = [=[Like that?!]=],
	["0407"] = [=[How's that!]=],
	["0408"] = [=[There!]=],
	["0409"] = [=[Want more?!]=],
	["0410"] = [=[Bleed!]=],
	["0411"] = [=[Die!]=],
	["0412"] = [=[Oh we're not done!]=],
	["0413"] = [=[That hurt?]=],
	["0414"] = [=[You trash!]=],
	["0415"] = [=[What, Thanatos?!]=],
	["0416"] = [=[You bastard, Thanatos!]=],
	["0417"] = [=[Get out of here, death god!]=],
	["0418"] = [=[Not your fight, Thanatos!]=],
	["0419"] = [=[Thanatos, again?]=],
	["0420"] = [=[Thanatos!]=],
	["0421"] = [=[Thanatos?!]=],
	["0422"] = [=[Do I know you, dead man?!]=],
	["0423"] = [=[This idiot again?!]=],
	["0424"] = [=[I didn't call for you!]=],
	["0425"] = [=[How did he get in?!]=],
	["0426"] = [=[Some friend you got, redblood!]=],
	["0427"] = [=[That skeleton again!]=],
	["0428"] = [=[What in the hell was that?!]=],
	["0429"] = [=[I know that damn boulder!]=],
	["0430"] = [=[The hell did that come from?!]=],
	["0431"] = [=[You need some help, redblood?!]=],
	["0432"] = [=[Fight me yourself, redblood!]=],
	["0433"] = [=[Can't handle me yourself, huh?]=],
	["0434"] = [=[You again?]=],
	["0435"] = [=[You again!]=],
	["0436"] = [=[Get lost!]=],
	["0437"] = [=[Stay out of this, I said!]=],
	["0438"] = [=[Get out of here!!]=],
	["0439"] = [=[Oh don't you mess with me!]=],
	["0440"] = [=[The hell you doing here?]=],
}
