AllDialogue.VoiceLines["Charon"] = {
	["0010?"] = [=[Haaahhhhh....]=],
	["0019?"] = [=[Hrrrrrnnnggghh...]=],
	["0038?"] = [=[Mmnnnrraaauuugggghhh!!]=],
	["0040?"] = [=[Nrrnnhhh, hnnnn, hrrnn, hrrrrrnnn...]=],
	["0045"] = [=[Hrrrnnnggghh....]=],
	["0046"] = [=[Grrnrnhh, rrraahhh!]=],
	["0047"] = [=[Hrraaaahhhhhh!!]=],
	["0073"] = [=[Hrrn... grrraaauuuggghh!!]=],
	["0074"] = [=[Rrnn... hhrraaaauuuggghh!!]=],
	["0075"] = [=[Grrr... nrrraauuuggghhh!!]=],
	["0076"] = [=[Urrh... urraaauuuggghh!!]=],
	["0077"] = [=[Krrr... krraauuuggghh!!]=],
	["0078"] = [=[Hhh, hrreehhhhh!!]=],
	["0099"] = [=[Haahh, nrraugh, haaaaah!!]=],
    ["0027"] = [=[Khhrraaa hhaaaaahhhh....]=],
	["0010"] = [=[Haaahhhhh....]=],
	["0011"] = [=[Mmmrrrrnnn....]=],
	["0012"] = [=[Hrrnmmmm....]=],
	["0013"] = [=[Khhhrrrrr....]=],
	["0015"] = [=[Hhrrrrnneehhhh....]=],
	["0016"] = [=[Urrrrrrgggghhh...]=],
	["0017"] = [=[Hrrrnnnhh....]=],
	["0019"] = [=[Hnnnggghhhh....]=],
	["0026"] = [=[Hrreehhh hohhhhhh....]=],
	["0111"] = [=[Nrrrrggghhh....]=],
	["0112"] = [=[Hrrnnaaauugghhh....]=],
	["0113"] = [=[Grrruuuooaahhh....]=],
	["0114"] = [=[Mmmrrnnngghh....]=],
	["0115"] = [=[Rrraaauuuggghhh....]=],
	["0116"] = [=[Hhrrrnn, haahhhhh....]=],
	["0117"] = [=[Urrrnngggghhh....]=],
	["0118"] = [=[Khhrrrnnnnnnggghh....]=],
	["0119"] = [=[Gggrrrnnngggghhhh....]=],
	["0120"] = [=[Heeehhh, hohhhhh....]=],
	["0002"] = [=[Rhhuuaaauuggghhh....]=],
	["0003"] = [=[Uunngggghhhh....]=],
	["0004"] = [=[Urrrnngghhhhh....]=],
	["0005"] = [=[Haaahhhhhhhhh....]=],
	["0006"] = [=[Hhhhaaaaaaahhh....]=],
	["0007"] = [=[Hhhaaaaaaahhh....]=],
	["0014"] = [=[Heeehhhhhhh....]=],
	["0018"] = [=[Nnnnrrrrrhhh....]=],
	["0020"] = [=[Hohhhh....]=],
	["0021"] = [=[Hrrrnnnn...?]=],
	["0022"] = [=[Hrrrn, hhmmm hmmmm....]=],
	["0023"] = [=[Hrrooooohhh....]=],
	["0025"] = [=[Hrrrhhrooooh, hnnnn....]=],
	["0036"] = [=[Hrrrrrrnnnnghhhhhhhh...]=],
	["0037"] = [=[Hrrrhhhaaaaauuugghhh...!]=],
	["0038"] = [=[Nnnrrraaaauggghhhh....]=],
	["0040"] = [=[Nrrnnhhh, hnnnn, hrrnn, hrrrrrnnn....]=],
	["0062"] = [=[Urrraaauuhggghh...]=],
	["0105"] = [=[Nrraaauuuggghhh...!]=],
	["0106"] = [=[Krrhh, hrraaaahhh...!]=],
	["0107"] = [=[Hhhrrrrhh... hhhrrrnnnn... hrrrrrhhh...]=],
	["0108"] = [=[...Ssss... kkkhhh... rrrrnngghhh... raauuuggghhh!!]=],
	["0109"] = [=[Hrrnngghh, grhhh, grhaaaaaaaahhhh...]=],
}
