AllDialogue.VoiceLines["Eurydice"] = {
	["0003"] = [=[Well don't you have your hands full, hon! I'll let you go, but there's one rule in my place, which is: Nobody leaves here empty-handed, you got that? So take your pick, my treat!]=],
	["0033"] = [=[Hey, nice of you to visit us, Your Royal Majesty! For you!]=],
	["0034"] = [=[Orphy and I, we're doing great here thanks to you. You take care, hon!]=],
	["0035"] = [=[Hope you find yourself someone to sing with, too, hon.]=],
	["0036"] = [=[Don't fret, Your Majesty, I'll have him back to work on time, you hear that, Orphy?]=],
	["0037"] = [=[Orphy and me, we're like your typical old married couple, hon.]=],
	["0038"] = [=[If you find happiness out there, hon, don't look back.]=],
	["0039"] = [=[Things aren't so bad here, hon. Hope you can say the same.]=],
	["0040"] = [=[What can I say, hon? We like practicing our favorite tune!]=],
	["0041"] = [=[Well if it isn't the Hades kid come to pay the both of us a visit!]=],
	["0042"] = [=[Just the ingredient I needed, hon, thank you so much! You know, you aren't near as bad as I'd heard!]=],
	["0043"] = [=[Aw, for me, really, Your Majesty? This will be perfect for my latest recipes.]=],
	["0044"] = [=[You read my mind, hon! I go through this stuff awful fast sometimes.]=],
	["0045"] = [=[Hey, mighty generous of you to keep me stocked up on this stuff, Your Royal Majesty!]=],
	["0046"] = [=[Thanks, Your Majesty! Though you're not going to get in trouble bringing me this stuff, are you?]=],
	["0048"] = [=[I ever tell you you're a real sweetheart, hon? Because, if not, I'm telling you right now. Where would my culinary practice be if not for you?]=],
	["0049"] = [=[Aw, that's awful sweet of you, Your Royal Majesty. Bringing me fresh ingredients like this! Know what, here's something for you, too, help keep you safe out there!]=],
	["0074"] = [=[Hey, hon, what's going on, speak up! I know when something's up down to my roots, and something's up.]=],
	["0075"] = [=[Orpheus said all that, huh? Tell you what, the next time you run into him, you ask him about the time that he came all this way to try and save me, even though I was already dead. Can you guess how that turned out?]=],
	["0076"] = [=[Yeah, well, neither did he! But you know what? Actions beat intentions, hon. Now, here, how about a treat and you can be on your way.]=],
	["0077"] = [=[Say, tell me something, there, Your Royal Majesty. You know a lot of shades. You wouldn't happen to know an Orpheus, would you? Spindly little thing, whiny voice? Heard he's officially serving in your court. Making music!]=],
	["0078"] = [=[You're mates, huh. Just as long as you don't count on him for anything. Hasn't even mentioned me, has he. Well if he ever does, you tell him I am doing great! I'm great.]=],
	["0079"] = [=[What is it, hon? Oh no, don't tell me you've come all the way from Tartarus to ask me more about your good-for-nothing court musician friend.]=],
	["0080"] = [=[So let me see if I understand. Orpheus blew it with me like an idiot, but now I'm supposed to be reaching out to him? Sorry, hon, but that's not happening. The two of us are finished. And, you know what? I think we're finished here, too. If you'll excuse me!]=],
	["0081"] = [=[Hey there, hon! So what do you think, pretty good tune, right? Don't know how come everybody doesn't sing. Lightens the mood, passes the time. What's not to like?]=],
	["0082"] = [=[Oh it's not Orpheus' song, you kidding me? This one's all mine. He always did like going on about how I'm his muse, well, that's 'cause I wrote half his songs for him! Bet he didn't mention that, did he.]=],
	["0083"] = [=[He can be a little hard to tolerate. A quality I hope isn't going to rub off on any of his mates. I should get back to practicing, see you.]=],
	["0084"] = [=[Tsk... and what am I supposed to do with that, Your Royal Majesty...?]=],
	["0085"] = [=[Don't think I will be running into him anytime soon from what I understand. But you're the Hades kid! You want to pull some strings on our behalf, go right ahead, I guess. But I won't hold my breath. Even if I could.]=],
	["0086"] = [=[So, uh, how's Orpheus been doing lately, anyway? Still keeping his hair in those neat little curls? I guess his tan must have faded by now.]=],
	["0087"] = [=[And now he knows I'm out there, still, huh. That's... well, thank you for the update, hon. Music's his gift. Good to know he's not thrown everything away.]=],
	["0088"] = [=[Yeah, sure, hon, what is it? Though you had better not be asking for my recipes. Closely guarded family secret! I'd say I'd take them to my grave, but... yeah.]=],
	["0089"] = [=[Your Royal Majesty, you want my song? You are aware it's called 'Good Riddance', right? Tsk, but sure, why not. If music's going to be playing in your House, it might as well be great. And let me give you something to go with it.]=],
	["0090"] = [=[...What'd he say, hon? I mean about the song. Bet he loved it, didn't he! But, I don't know for sure. And I've been wondering, kind of a lot, I guess.]=],
	["0091"] = [=[Huh. So it's a hit, is what you're saying, then. I had a feeling about that one. Sometimes you put some words together and right then and there, you know that you've got something special.]=],
	["0092"] = [=[What happens now, hon...? What I mean is... now you got me thinking about Orpheus again, so... what am I supposed to do with that?]=],
	["0093"] = [=[Well, what can I tell you? Thanks, Your Royal Majesty. That means a lot. No pressure, though. I've been all right without him all this time, and I will be all right, no matter what. If only he could say the same.]=],
	["0094"] = [=[Now don't you start with that again, you get me, Orphy? Got our whole entire afterlives ahead of us! And lots of songs to catch up on.]=],
	["0095"] = [=[Yeah. So, if you would excuse us for a little while, hon? I'm not finished catching up with him just yet. But first, before you go!]=],
	["0096"] = [=[Orphy still just can't shut up about that time, hon. But we're making progress. Thanks for having him stop by. I'm sure he needed plenty of encouragement.]=],
	["0097"] = [=[Hey, listen here a moment, Hades kid. Look, I... Thank you. From the bottom of my heart. For bringing Orphy back to me again, and everything.]=],
	["0098"] = [=[Well, you're a real sweetheart, hon. You'll still be seeing Orphy all the time around your House, but now, I get to see him, too. Nice having something to look forward to, you know? Bet someone out there feels that about you.]=],
	["0099"] = [=[Oh, not just any plants, hon! Trees! Big gnarled oaks and things. Some of them live hundreds of years! Way up there as mortals go. You take good care of it like that, maybe it'll grow to be something special for you, too!]=],
	["0100"] = [=[Yeah, I'm part oak, that's right. But maybe not the part you're thinking of, I mean, you think I would just hand you one of my babies or something? Hahahaha, that's disgusting!]=],
	["0101"] = [=[How long have I been down here, hon? Huh! I don't have the faintest. You lose your sense of time once you're a shade, or maybe once there's not a sun or moon over your head. But yeah, I found myself a decent spot and fixed it up a bit!]=],
	["0102"] = [=[You're just in time, Your Royal Majesty! Got something real good cooking right here that you are going to love. You hungry, yeah?]=],
	["0103"] = [=[What, you think I get a lot of guests, here? Haha, no, but I like cooking anyway! It's like singing, in a way. Keep getting better the more you try, turns out a bit different each time.]=],
	["0104"] = [=[The searing heat? Haha, I am dead, Your Royal Majesty! Searing's just a cooking technique to me. Don't need to sleep, either! I can just keep cooking up a storm. It's not so bad!]=],
	["0105"] = [=[Yeah, gods that can die! How is that fair? Was just a stupid snake bite in my case, can you imagine something more embarrassing? You're just minding your business, and then snap! You're dead, and on your way down here.]=],
	["0106"] = [=[Well, I was going to end up here sooner or later. Might as well while I'm still looking good. Though, I guess you do kind of get to lock in whatever age when you register. Bet everybody dying of old age pushed that one through.]=],
	["0107"] = [=[What's your official business, anyway, Your Royal Majesty? Seems like it's bringing you through Asphodel an awful lot lately.]=],
	["0108"] = [=[Oh really! Say no more, I know how that is. Hope the Fates will look the other way for you. Getting out of here, huh. Not thought of that myself in I don't know how long...]=],
	["0109"] = [=[Of all the lava rocks in Asphodel, the Hades kid found this one once again, wouldn't you know! You got a map or something to this place, or what?]=],
	["0110"] = [=[Coincidence? Come on, hon, you're a god. Someone out there is sending you my way. Maybe it's just the Fates. Ah well! I sure don't mind a little company. And I have lots to eat!]=],
	["0172"] = [=[Hey you must be the Hades kid! How's it going, then, Your Royal Majesty? Nice to meet you, I'm Eurydice. What brings a big important guy like you up to a place like this?]=],
	["0173"] = [=[Well don't you have your hands full, hon! I'll let you go, but there's one rule in my place, which is: Nobody leaves here empty-handed, you got that? So take your pick, my treat!]=],
	["0174"] = [=[He put you up to this? Look, hon, why don't you get on with your business, then. But you can't leave empty-handed, that's the rule, so take your pick, my treat! Nothing for him, though.]=],
	["0175"] = [=[Hey, what's up, hon? Say, you must know a lot of big shots, don't you? Other gods and all that?]=],
	["0176"] = [=[Oh, that's sweet of him! Nice enough guy, for an Olympian. Yeah, he was the one who dropped me off here in the first place. No hard feelings here, he was just doing his job. It was Orpheus who messed everything up.]=],
	["0177"] = [=[Hold on, hon, is that... huh! Almost felt like Orpheus was with you there. Would you listen to me? Must have been singing too many high notes, or something.]=],
	["0179"] = [=[What's the latest, hon, anything been happening down in your fancy House lately?]=],
	["0180"] = [=[Not following instructions, huh. Sounds like Orpheus, all right. Well, if that's the most exciting thing you've got going on, then I haven't missed much being out here.]=],
	["0181"] = [=[Hey! What's the matter, Your Royal Majesty? You're looking kind of down. Normally you're all smiles, for whatever reason!]=],
	["0182"] = [=[Oh, that? Pff, come on, don't even worry about it. If you were being too pushy, you better believe I would have put you back in your place, royalty or not. But hey, can't ever be too careful when it comes to people's past and feelings and stuff, right?]=],
	["0195"] = [=[You been snacking on onions or something, there, hon? No offense or anything, but you smell like you ate a whole one of them raw.]=],
	["0196"] = [=[What, are you kidding me? You can grill them, sautÃ© them, fry them, boil them, pickle them, roast them! Oh, hon. You've been missing out.]=],
	["0206"] = [=[Sure don't see a lot of other nymphs around here, huh! We don't die too easy, most of us. Makes me feel all special!]=],
	["0207"] = [=[That's what I heard! Though it's not like we all hang out, I mean, you've got the dryads, and the naiads, and the nereids, and the oceanids... pretty much every type of terrain up top, there's a kind of nymph who loves it! Maybe we need a name for Underworld nymphs, too.]=],
	["0208"] = [=[NPC_Eurydice_01]=],
	["0209"] = [=[You know this tune, hon? It's one of our old hits!]=],
	["0210"] = [=[We were just thinking about old times, Orphy and I!]=],
	["0211"] = [=[Thought we'd mix up our singing just a bit here, hon!]=],
	["0212"] = [=[Got to tell you I've warmed up to this old song over the years!]=],
	["0213"] = [=[Oh, her? Yeah, she was with Hades Senior, why? Wait. Whoa. Are you...? I thought...]=],
	["0214"] = [=[Didn't get much of an impression, but I can tell you this: She had good taste in music! Orpheus and I, think we won her over with our little duet. Haven't seen or heard from her lately, though. Look, I hope everything's OK.]=],
	["0215"] = [=[Hey, everybody's saying Persephone... she's back? That sounds like a bit of good news, there, isn't that right, hon?]=],
	["0216"] = [=[Well, that's a relief. And, you're still here! So I guess you've got more official business to take care of, which means I've still got somebody to taste-test for me every now and then!]=],
	["0217"] = [=[Orphy tells me the Queen, she's been settling in just fine down at your House! Must be different having a lady like that around. How's Hades Senior taking it, if I may ask?]=],
	["0218"] = [=[Glad to hear it! Orphy always liked singing for an audience more than I did, and it sounds like she's a good one.]=],
	["0233"] = [=[Got to tell you, hon. Orpheus sure is different since last he and I met. You know, back when he was still living and breathing and all.]=],
	["0234"] = [=[Oh, we're getting along great! Better than ever. He used to be a bit more of a hotshot, but now it's like, he's a little more... what's the word... sensitive? Now I can always tell exactly what's on his mind.]=],
	["0235"] = [=[Hey, Your Royal Majesty! I must say you've accomplished some truly amazing feats, according to Orphy at least! But don't worry. Your secret's safe with me.]=],
	["0236"] = [=[That modesty won't get you anywhere with me, either, hon, Your Greatness. I'm honored to merely be in the presence of one with so many wild exploits to sing or speak of!]=],
	["0237"] = [=[Whoa, this is Ambrosia! Hard to come by this stuff around here. You sure I can have this?]=],
	["0248"] = [=[Guess what we've been up to lately, hon? Now if you'll excuse us?]=],
	["0249"] = [=[We just finished eating, here! Got plenty left over.]=],
	["0250"] = [=[The one thing better than singing, hon, is singing with somebody you love.]=],
	["0251"] = [=[Orphy here's just practicing for when he's got to sing next for Hades Senior!]=],
	["0252"] = [=[What do you know, we were just in the middle of a song here, hon!]=],
	["0253"] = [=[Not much luck trying to teach Orphy to cook, but he can sing, all right!]=],
	["0254"] = [=[Look, Orphy, we've got an audience! So sing your heart out!]=],
	["0255"] = [=[Don't mind Orphy, here, hon. Can't snap him out of it once he gets singing!]=],
	["0263"] = [=[You got anyone special in your life, by the way, hon? You seem like you'd be good for somebody out here.]=],
	["0264"] = [=[Know what you mean. And hey, that's great! Long as you can still be yourself. I've known too many nymphs, their whole lives revolved around somebody they loved. I bet whoever it is that loves you... it's because of who you are.]=],
	["0265"] = [=[You ever play any music, or sing or anything yourself, Hades kid? It's good for you, you know!]=],
	["0266"] = [=[Well, might I recommend giving it a shot at some point? Who knows, you might be the next Orpheus!]=],
	["0267"] = [=[He did! And a tan is like... well, when you stay out in the hot sun up there long enough, your skin kind of starts to bake a little bit. But nicer than that sounds! Got to say, though, the years have been kind to Orphy, don't you think?]=],
	["0268"] = [=[Didn't get much of an impression, but I can tell you this: She had good taste in music! Orpheus and I, think we won her over with our little duet. Haven't seen or heard from her lately, though.]=],
	["0178"] = [=[Oh, that's him in there all right! See, I never should have second-guessed myself. Well, you hang onto that, as I've got plenty memories of him already, thanks!]=],
	["0202"] = [=[Oh, hon, you look awful. What did you get yourself into? Here, one of these should make you feel a little better.]=],
	["0203"] = [=[Oh, you look like you've been through a lot, Hades kid. Maybe a decent bite to eat will help!]=],
	["0204"] = [=[Oof, you're a mess, there, hon. You save your strength and see if this will do you any good.]=],
	["0205"] = [=[Hey, don't go bleeding on my floor, hon. I just cleaned the place! Take one of these, maybe it'll tide you over.]=],
	["0005"] = [=[Why not have a quick bite of something to eat before you head on out, hon?]=],
	["0006"] = [=[Sing when you're happy, sing when you're not, Your Royal Majesty.]=],
	["0007"] = [=[Hey, it's the Hades kid! So what's it going to be this time, Your Royal Majesty?]=],
	["0008"] = [=[I'd say make yourself at home, hon, but you look like you got cooler places to be!]=],
	["0009"] = [=[You are just in time, Your Royal Majesty! Cooked up something special just for you.]=],
	["0010"] = [=[Why, Your Royal Majesty, you're back! Well, see you later!]=],
	["0011"] = [=[And here I was just thinking it's been too long since the Hades kid stopped by!]=],
	["0012"] = [=[So what'll it be this time, Your Royal Majesty, hmm?]=],
	["0013"] = [=[Oh you look positively famished, hon! Here let me help with that.]=],
	["0014"] = [=[You must be hungry, hon. Got something ought to keep you going!]=],
	["0015"] = [=[How nice of you to stop on by, Your Royal Highness! Here!]=],
	["0016"] = [=[How's it going lately, hon, you eating well and everything?]=],
	["0017"] = [=[Just singing to myself and cooking up a storm. You know me, hon.]=],
	["0018"] = [=[Eat up, hon! Not like I got other mouths to feed!]=],
	["0238"] = [=[All's well in Asphodel, Your Royal Majesty! You take care of yourself. I'll be here.]=],
	["0240"] = [=[You want the best cooking in all of Asphodel, you know where to go!]=],
	["0241"] = [=[Hey, it's the Hades kid! What's it going to be this time, hm?]=],
	["0242"] = [=[Take care of yourself out there, all right, Your Royal Majesty?]=],
	["0243"] = [=[Don't let Hades Senior get you down, hon. Here.]=],
	["0244"] = [=[I know you've got important business to attend to, so thanks for checking in, Your Royal Majesty.]=],
	["0245"] = [=[You look like you're in a rush, though there's always time for a quick snack, right?]=],
	["0246"] = [=[Hey, welcome back, Your Royal Majesty, you're just in time!]=],
	["0247"] = [=[Been trying to perfect these recipes for I don't know how long!]=],
	["0138"] = [=[You look like you haven't eaten since you were here last!]=],
	["0136"] = [=[You're always welcome here Your Royal Majesty.]=],
	["0135"] = [=[I get you something for the road there, hon?]=],
	["0134"] = [=[What's it going to be, Your Royal Majesty?]=],
	["0019"] = [=[You just be sure to tell that good-for-nothing Orpheus I'm looking good.]=],
	["0020"] = [=[Hon, I'd ask how old what's-his-name is doing, but I don't even care!]=],
	["0021"] = [=[Bet you Orpheus hasn't had any strokes of musical genius lately, now, has he?]=],
	["0022"] = [=[Better not be Orpheus putting you up to visiting here all the time like this.]=],
	["0023"] = [=[This song's better than anything Orpheus ever came up with I can tell you that.]=],
	["0024"] = [=[If you'll excuse me, Your Royal Majesty, I'm not exactly in the mood for an extended chat.]=],
	["0025"] = [=[You best have no more messages from no-good Orpheus this time.]=],
	["0026"] = [=[Here, have a snack, hon, and tell Orpheus it was delicious.]=],
	["0027"] = [=[You keep an eye on Orpheus for me, all right, hon?]=],
	["0028"] = [=[Do one thing for me, hon. Make sure Orpheus knows I'll be right here.]=],
	["0029"] = [=[I've got to be honest with you, hon. Sometimes I kind of miss him.]=],
	["0030"] = [=[Sometime you'll visit me like this and Orpheus is going to be here too.]=],
	["0031"] = [=[Don't let Orpheus get into too much trouble, won't you, hon?]=],
	["0032"] = [=[I'm fine here on my own, hon. But, I wouldn't mind if he was here.]=],
	["0197"] = [=[Hope Orpheus is on the up-and-up down where you live.]=],
	["0198"] = [=[I'd ask you to bring one of these to Orpheus, but they're no good unless they're perfectly fresh.]=],
	["0199"] = [=[Orpheus tells me you've been a good friend. Thanks, hon.]=],
	["0200"] = [=[I love Orpheus and all, hon, but it's nice having a little time here to myself!]=],
	["0201"] = [=[I know you can't stay long, hon, so eat up and stay safe out there, all right?]=],
	["0239"] = [=[I sing when Orpheus is here, I sing when he isn't. Simple!]=],
	["0004"] = [=[He put you up to this? Look, hon, why don't you get on with your business, then. But you can't leave empty-handed, that's the rule, so take your pick, my treat! Nothing for him, though.]=],
	["0050"] = [=[You know, you're much more generous than you get credit for, Your Majesty! I'm feeling pretty generous, myself, so here! I want you to have this.]=],
	["0051"] = [=[Who's there?]=],
	["0052"] = [=[Yeah, what do you want? Oh!]=],
	["0053"] = [=[Someone there?]=],
	["0054"] = [=[Oh hey!]=],
	["0055"] = [=[Hi hon!]=],
	["0056"] = [=[Hey hon!]=],
	["0057"] = [=[Hey you!]=],
	["0058"] = [=[Hey!]=],
	["0059"] = [=[Majesty!]=],
	["0060"] = [=[Majesty.]=],
	["0061"] = [=[Look-ee who.]=],
	["0062"] = [=[Hi!]=],
	["0063"] = [=[Welcome!]=],
	["0064"] = [=[Come on in!]=],
	["0065"] = [=[Make yourself at home.]=],
	["0066"] = [=[Everybody!]=],
	["0067"] = [=[Come on!]=],
	["0068"] = [=[Sing it with me!]=],
	["0069"] = [=[Sing it!]=],
	["0070"] = [=[Yeah!]=],
	["0071"] = [=[That's it!]=],
	["0072"] = [=[Give yourself a hand!]=],
	["0073"] = [=[You're a natural!]=],
	["0111"] = [=[Well, see you!]=],
	["0112"] = [=[Careful, hon!]=],
	["0113"] = [=[Take care, yeah?]=],
	["0114"] = [=[Farewell Your Majesty!]=],
	["0115"] = [=[Bye!!]=],
	["0116"] = [=[OK bye!]=],
	["0117"] = [=[Later then, yeah?]=],
	["0118"] = [=[Smooth sailing!]=],
	["0119"] = [=[Stay cool!]=],
	["0120"] = [=[See you next time!]=],
	["0121"] = [=[Come again!]=],
	["0122"] = [=[You can do it!]=],
	["0123"] = [=[Enjoy!]=],
	["0124"] = [=[That one's on me!]=],
	["0125"] = [=[Here you go!]=],
	["0126"] = [=[All yours!]=],
	["0127"] = [=[Freshly made!]=],
	["0128"] = [=[You got it!]=],
	["0129"] = [=[Sure thing!]=],
	["0130"] = [=[Sounds good!]=],
	["0131"] = [=[For you!]=],
	["0132"] = [=[What can I do for you, hon?]=],
	["0133"] = [=[What do you need, hon.]=],
	["0137"] = [=[Yeah, what is it?]=],
	["0139"] = [=[Hey, Your Royal Majesty, to what do I owe the pleasure?]=],
	["0140"] = [=[You got it, hon!]=],
	["0141"] = [=[Coming right up!]=],
	["0142"] = [=[Sure thing, hon.]=],
	["0143"] = [=[It'll be my pleasure.]=],
	["0144"] = [=[Hah, I knew it!]=],
	["0145"] = [=[Oh good choice there, hon.]=],
	["0146"] = [=[You bet!]=],
	["0147"] = [=[As you wish, Your Royal Majesty.]=],
	["0148"] = [=[That can be arranged.]=],
	["0149"] = [=[Sounds good, no problem!]=],
	["0166"] = [=[<Chuckle>]=],
	["0167"] = [=[<Chuckle>]=],
	["0168"] = [=[<Laugh>]=],
	["0169"] = [=[<Laugh>]=],
	["0170"] = [=[<Scoff>]=],
	["0171"] = [=[<Scoff>]=],
	["0184"] = [=[Come on, now.]=],
	["0185"] = [=[Not now.]=],
	["0186"] = [=[Hey!]=],
	["0187"] = [=[Please.]=],
	["0188"] = [=[Let me sing.]=],
	["0189"] = [=[Excuse me!]=],
	["0190"] = [=[Eh!]=],
	["0191"] = [=[Whatever!]=],
	["0192"] = [=[Sorry, singing!]=],
	["0193"] = [=[Really, hon?]=],
	["0194"] = [=[Having fun?]=],
	["0183"] = [=[Come on.]=],
	["0219"] = [=[See you!]=],
	["0220"] = [=[Take it easy!]=],
	["0221"] = [=[Take care!]=],
	["0222"] = [=[Bye, hon!]=],
	["0223"] = [=[Stay safe!]=],
	["0224"] = [=[Safe travels!]=],
	["0225"] = [=[Good choice!]=],
	["0226"] = [=[Excellent.]=],
	["0227"] = [=[Coming right up!]=],
	["0228"] = [=[Try this!]=],
	["0229"] = [=[Sure, here!]=],
	["0230"] = [=[Careful, it's hot!]=],
	["0231"] = [=[Here, enjoy!]=],
	["0232"] = [=[Hope you like it!]=],
	["0256"] = [=[Hades kid!]=],
	["0257"] = [=[Hey!]=],
	["0258"] = [=[Welcome back!]=],
	["0259"] = [=[Come in!]=],
	["0260"] = [=[What's going on?]=],
	["0261"] = [=[Look, Orphy!]=],
	["0262"] = [=[Look who, Orphy!]=],
}
