AllDialogue.VoiceLines["Orpheus"] = {
	["0051"] = [=[Why, this is absolutely splendid, Zagreus. Is this really for me? It's so very kind of you to think of me like this.]=],
	["0052"] = [=[Oh, I, certainly, why, I don't see why not. I mean, it's not as though I've got something to do that isn't that.]=],
	["0053"] = [=[...And, anyways, I oughtn't have looked back, I mean, the moral of the story is to not look back when you are told not to look back, you understand, don't you, my friend?]=],
	["0054"] = [=[...I quite enjoyed our outing, Zagreus. So, I suppose I shall be seeing you around?]=],
	["0055"] = [=[Oh, why! I'm very much obliged that you have thought of me again, for such a wonderfully thoughtful gift!]=],
	["0056"] = [=[You're always much too kind, you know, my friend? Now typically I would express my gratitude through song, except, you understand, don't you?]=],
	["0057"] = [=[Oh, my, but you can't simply be this kind to me without retaliation on my part, my friend! And so, in turn, I have a gift for you!]=],
	["0066"] = [=[Oh, hello Zagreus. I was just wondering if you had ever heard of any other court musicians who had lost the will to sing? Your father's asked me to explain myself and honestly it has been rather difficult.]=],
	["0068"] = [=[Oh, hello Zagreus. You look a little down. And so I was just wondering, would you perchance fancy a song right now?]=],
	["0069"] = [=[Oh, fancy that one do you? Alas, I've not the heart to sing it anymore. I'm glad you like it, though.]=],
	["0070"] = [=[Why, it's that I have lost my muse, my friend. It isn't harder to explain than that. Have you not had such moments in your life, where you had lost the will to chase your passions?]=],
	["0071"] = [=[And I am truly happy for you, friend. Alas, I've had no luck in my own search, not that I'm searching any longer, so, I'll just be over here, OK?]=],
	["0072"] = [=[I fear my muse is long since lost to me, my friend, though truly thanks for asking. I suppose she must be out there somewhere still, since I once traveled 'cross this land in search of her, and found her then. But that was quite a while back.]=],
	["0073"] = [=[Well, this was back when I was still alive, you understand. Your father, why, he doesn't care for anyone to leave this realm, and, basically now I'm stuck here as well! Not seen her since, and, I'm not much for travel anymore.]=],
	["0074"] = [=[I appreciate the sentiment, my friend, though please don't worry about her or me. I mean, we're dead! We're fine.]=],
	["0076"] = [=[Thank you for listening, my friend. Eurydice, she likewise used to listen to me all the time....]=],
	["0077"] = [=[I understand you've journeyed well beyond the pits of Tartarus, my friend? Another most heroic feat of yours, and truth be told I find it quite inspiring.]=],
	["0078"] = [=[Oh, that's a rather bold insinuation, Zagreus. I don't know that I've the will for that, I... just, I need some time to think, is that all right?]=],
	["0079"] = [=[My, that is wonderful to hear, my friend! Another in a litany of such heroic deeds, more noble than the heroes of our verse, and even great Achilles over there!]=],
	["0080"] = [=[Why, that is a spectacularly vivid tale, Zagreus, and most deserving to be chronicled in song! Would that there were a poet here still willing to commit such deeds to verse.]=],
	["0081"] = [=[But that is such a splendid tale, Zagreus, deserving to be sung both far and wide, until it turns into the stuff of myth, as deathless as the gods themselves! I'll gladly tell that one about!]=],
	["0082"] = [=[But, Zagreus, that is a striking revelation, the connection you describe. I see it! I can see it now! To think the god of wine and you are intricately linked, it isn't obvious, is it?]=],
	["0083"] = [=[Your tale stirs my soul, it truly does, my friend. It is a marvel to me that such heroism isn't widely known, and I'm committed to the spread of all such truths.]=],
	["0084"] = [=[Oh, Zagreus! There isn't need for such humility, not when one's deeds of heroism are as great and numerous as yours! It is an honor to have heard such deeds first-hand!]=],
	["0085"] = [=[Come now, my friend! I know this is a test of faith! Of course I am committed to the spread of such heroic deeds as yours. And I do so enjoy getting to hear them first!]=],
	["0088"] = [=[I've decided I should give this singing thing another shot for now, my friend. I hope you like it.]=],
	["0089"] = [=[Oh no, I never found my muse, my friend. It's just... seeing you carrying on like this time after time, I was reminded I ought to get on with my life, too, such as it is right now.]=],
	["0090"] = [=[...You're much too modest, Lord Achilles, for someone with such a number of heroic deeds and glorious decapitations to his name! You ought to be more like ever-boastful Zagreus, and talk it up some more!]=],
	["0096"] = [=[...You called upon your humble court musician, as I understand, Lord Hades sir? Referring to myself of course?]=],
	["0097"] = [=[Oh, that. I must apologize, again, Lord Hades sir. For I'm afraid that I've no wish to sing as yet. In spite of your persuasiveness even. And, that, um, is my final word upon the subject. At this time.]=],
	["0098"] = [=[If I may be so bold, my lord? Perhaps the merest sight of me still stirs in you a memory of my performances of yore. It gladdens me you used to like my songs.]=],
	["0099"] = [=[Technically, one ought consider it a hymn, my friend! In honor of your numerous travails, prior to your current set of circumstances, which must pale in comparison to all the rigors you've endured to date!]=],
	["0100"] = [=[Heavens, no, my friend! Your humility is matched only by your perseverance in the face of adversity! May your great deeds live on forever, much like you!]=],
	["0124"] = [=[What? Why... yes. I know Eurydice. Or, I once knew her, I should say. Whyever would you ask me such a thing, my friend?]=],
	["0125"] = [=[We more than knew each other, Zagreus. We were husband and wife. She was my muse. To think that we are doomed to be apart during our afterlives. Ah, well!]=],
	["0126"] = [=[I do not wish to trouble her again, my friend. Speak not to her of me, all right? I have my memory of her; it is enough.]=],
	["0127"] = [=[What? Why... truly. I knew Eurydice resided in your father's realm, but... I had not anticipated you would cross her path. You're certain of this, then?]=],
	["0128"] = [=[We were much more than that, Zagreus. We were husband and wife. She was my muse. To think that we are doomed to be apart during our afterlives. Ah, well!]=],
	["0129"] = [=[You what?! Or, what I meant to say was: Oh. Did you perchance get the impression she yet harbors toward me feelings of resentment, and the like?]=],
	["0130"] = [=[Oh, it's just... I almost saved her soul from this domain, back when I lived and breathed. But in the final moments of my rescue, my faith faltered. She is lost to me forever, now. Though, I'm pleased to hear she isn't lost to you!]=],
	["0131"] = [=[Almost, my friend, almost. But in the final moments of my rescue, my faith faltered. She is lost to me forever, now. Though, I'm pleased to hear she isn't lost to you!]=],
	["0132"] = [=[Pray tell me something, Zagreus. How is she lately, hm? Eurydice, I mean. Her hair, fall colors, or full bloom? Her poise, as proud and supple as the oak?]=],
	["0133"] = [=[Alas, I cannot change the past, my friend. So, no. As you can plainly see by now, I'm dead to her. Rightfully so, at that.]=],
	["0134"] = [=[Don't I want to see my Eurydice again...? Why, yes. That, more than anything, my friend. Provided she wanted to see me. I tried once to disturb her everlasting rest, as you well know. And that did not pan out as I had hoped....]=],
	["0135"] = [=[What news of late about Eurydice, my friend? She is as delicate as I described, no doubt? Ah, but... I am dwelling on her once again, it seems.]=],
	["0136"] = [=[How very understandable, indeed. Were I to have been failed to be rescued from the depths of hell, mere moments from escape, I too would be quite cross with my attempted rescuer. And for quite some time.]=],
	["0137"] = [=[I have no knowledge of the weavings of the Fates, my friend. Perhaps they trample on what used to be my heart for leisure or for sport, do you suppose?]=],
	["0138"] = [=[I must confess something to you, my friend. My mind still wanders to Eurydice quite often, and my memories of her. Despite my best attempts to move along with my existence here. I would call it a fatal flaw, except, I am already dead.]=],
	["0139"] = [=[I, too, once had ideas, Zagreus. Ideas, and inspirations. It was so very wonderful, to have a muse...]=],
	["0140"] = [=[My friend, you wrote a song, for me...? Oh, but this is not from you, it's from... Eurydice... I, no, I don't know what to say, I... I...]=],
	["0141"] = [=[Oh. Thanks for the sentiment, my friend, it's just... when I sing this song of hers, why, I've this feeling where my heart once was that, well... perhaps she can.]=],
	["0143"] = [=[I think you're right. I am so very anxious, I must say. But I must also thank you, for this opportunity, and... for speaking with me all this time. So, how might I repay you?]=],
	["0144?"] = [=[Zagreus! The most amazing circumstances have occurred. The terms of my employment, they've been altered such that... I may visit Asphodel sometimes. May visit her.]=],
	["0146"] = [=[Oh, things are going very wonderfully, my friend. I never thought I'd see Eurydice again, after I...]=],
	["0147"] = [=[It was more than all right, my friend. Why, it was positively inspirational. But I've returned as promised to this House. My love is there, whilst my responsibilities are here.]=],
	["0148"] = [=[Oh, on the contrary, Zagreus. It dawned upon me that having some distance between my responsibilities and my domestic life, why... it is not so bad. Besides, Charon makes travel to and fro quite simple for me, really.]=],
	["0149"] = [=[A splendid compliment, my friend. Doubtless the Fates themselves conspired to ensure Eurydice and I would meet, and sing together. Fall in love. And then be cruelly separated for some time!]=],
	["0150"] = [=[Why, you're correct of course, my dear. If you'll excuse us, Zagreus? Our calling beckons.]=],
	["0151"] = [=[How kind of you, my friend. It's just... seeing you carry on like this, time after time, I was reminded I ought to get on with my existence, too. Such as it is right now.]=],
	["0152"] = [=[Are you the one whom I should thank for this most wondrous music stand, my friend? Why, it is positively splendid, isn't it?]=],
	["0153"] = [=[Who can explain the secret art of Daedalus, my friend? Know only that, whenever it produces music for your listening enjoyment, that the sound you hear is coming from my soul!]=],
	["0154"] = [=[No, Zagreus. Unless of course you wanted to set loose a cherished living memory of mine, and take from me that fleeting bit of joy?]=],
	["0155"] = [=[I'm glad you like it, Zagreus. Some memories are cherished, yes, indeed. But there can come a point where they provide more benefit to others than ourselves. Don't you agree?]=],
	["0177?"] = [=[It's awfully quiet here, you know, when you're out and about? Makes me a bit self-conscious, truth be told, seeing as ostensibly I'm the musician of this court.]=],
	["0184"] = [=[Your father can be.... most persuasive, yes, my friend. However, this time, I am... putting my foot down! I have no plans to sing for him again.]=],
	["0185"] = [=[I... no. Please. My muse is gone to me. I can do no such thing.]=],
	["0186"] = [=[Oh, hello, Zagreus. I understand you liberated me from my eternal punishment. And so I have returned to serve your father here. Thanks.]=],
	["0187"] = [=[OrpheusUnlockItem]=],
	["0194"] = [=[I'm gladdened that my songs yet stir your soul, my lord. But, I have to confess my choice to sing again was motivated largely by the Prince. And by my muse, of course.]=],
	["0195"] = [=[You always offer means to quench my thirst, my friend. A wonder that I have such feelings, even now.]=],
	["0196"] = [=[I am indebted to you, Zagreus, both for your friendship and embarrassment of generosity.]=],
	["0197"] = [=[Ah, but this is splendid, Zagreus. And I must say, apart from my Eurydice, I've never felt as strong a bond of kinship as with you.]=],
	["0198"] = [=[Please, my friend! I feel I am undeserving of such a relentless show of kindness on your part. I shall accept, but you'll relent, won't you? As well as forgive me?]=],
	["0209"] = [=[I owe my everything to my Eurydice. She authored many of my songs, indeed; and she inspired many, many more. Whilst living, we collaborated frequently, you see.]=],
	["0210"] = [=[It is but one of life's injustices, I fear. I always sang her praises every chance I had. And she asserted herself splendidly. Yet even still, our listeners believed our songs, they came from me... what else could I have done?]=],
	["0211?"] = [=[Say, Orpheus, Eurydice told me your songs, some of them came from her? She seems quite brilliant. You choose your muses well!]=],
	["0212"] = [=[Oh, why, I learned from many different sources, Zagreus. That is before all of my inspiration started coming from a single source. I credit my accomplishments to her, and to Apollo, and the gods. And to considerable time spent practicing!]=],
	["0214?"] = [=[Have you considered doing music-making as a recreational pursuit, my friend? You have such slender hands, why, I believe you'd do quite well at it.]=],
	["0215"] = [=[Oh, why, that's splendid, Zagreus. And I can certainly show you a thing or two. First, the proper posture is important, here...]=],
	["0216"] = [=[...now remember to practice the plucking technique which I taught you, and mind your off-hand constantly. And, above all, continue practicing! The joyfulness is in the practicing itself.]=],
	["0217"] = [=[Zagreus, I heard your recent lyre-playing from your bedchambers. Let no one lead you to believe it's not a reassuring start.]=],
	["0218"] = [=[I'm being serious, my friend. It is a challenging pursuit requiring a dedicated state of mind. The progress shall come. You shall discover what I mean.]=],
	["0220?"] = [=[Your music-playing has improved substantially. Perhaps in time you shall surpass my own abilities!]=],
	["0221"] = [=[I must commend you on the most splendid lyre-playing emanating from your bedchambers, my friend. It seems we have a second court musician, now.]=],
	["0222"] = [=[Oh, haha, but your concern is much appreciated, friend. I feel I am in everlasting bliss. It simply does not show upon my countenance. Perhaps through song is how I best express myself.]=],
	["0223"] = [=[I scarce can possibly imagine such a spectacle, my friend! But certainly I shall attempt to try!]=],
	["0224"] = [=[Of course I do, my friend! Though, you must know, your father has requested his relationship to you be kept quite clandestine. You'll understand if I not sing your praises in this case, won't you?]=],
	["0226"] = [=[Oh, on the contrary, sir, I am profoundly satisfied. We are most fortunate to have employment even after death. Imagine, merely resting for eternity, when you could work!]=],
	["0229"] = [=[Oh, that was kind of him, my friend! When I first ventured deep into this realm, whilst searching for the soul of my lost muse... after I failed utterly, it was Lord Hermes who whisked her away. It happened so fast. He did an excellent job!]=],
	["0230"] = [=[How kind of you. It's just... seeing you carry on like this, time after time, I was reminded that I might as well get on with my existence, too. Such as it is right now.]=],
	["0231"] = [=[I became so enthralled with song once more, my friend, that I have been inspired to compose another one. For old time's sake, perhaps.]=],
	["0232"] = [=[How kind of you, although... my voice is nothing but the crunch of gravel underfoot compared to hers, which soars as though on wings.]=],
	["0233"] = [=[My muse... never has somebody been as splendorous as my Eurydice...! She was so gentle, yet so stout of heart that it would make yours ache, just thinking on it. She inspired innumerable songs of mine.]=],
	["0234"] = [=[Oh, it is certainly my pleasure, Zagreus. This song of Eurydice's and mine, I've a connection to it, I suppose. Reminded me of some fond memories!]=],
	["0244"] = [=[I shall be happy to oblige, my lord. Eurydice and I are grateful for your magnanimity.]=],
	["0245"] = [=[You're sorry, Zagreus? Whatever for? If not for you, I fear I never would have seen my muse again.]=],
	["0246"] = [=[But, you didn't make things worse, my friend. And... truth be told, I do not think I ever would have asked for help, at any point, because... I don't entirely know how. So I am grateful to you, and your generous instinct.]=],
	["0247"] = [=[Why, I don't know, my friend. Once people set their minds to certain things... it can be difficult to show them other possibilities exist. What's to be done?]=],
	["0248"] = [=[Get the word out...? But I am court musician of this House. My songs no longer reach too many ears. Although... I do suppose all of these shades about... they are my audience, as well. I shall make certain that they know whose songs I sing.]=],
	["0249"] = [=[...You must know, you sound as wonderful as ever, now, my dear!]=],
	["0250"] = [=[Is she not truly wonderful, my friend?]=],
	["0251"] = [=[We sing, and sing, and never once grow weary, Zagreus!]=],
	["0252"] = [=[I never thought I would see her again. You are to thank for this, my friend.]=],
	["0253"] = [=[When we thus sing together, Zagreus, I lose all track of time.]=],
	["0254"] = [=[Is the singing of Eurydice not the most splendid thing that you have ever heard?]=],
	["0255"] = [=[Shall there ever be a voice as lovely as Eurydice's, my friend?]=],
	["0256"] = [=[It gladdens me that you could join us here, my friend.]=],
	["0257"] = [=[Almighty Nyx appears to tolerate my presence, Zagreus. For she could cast me into everlasting darkness if my song failed to be pleasing to her. She is a most-discerning listener!]=],
	["0258"] = [=[Oh, that one, yes, I know! I mean, it was a favorite, I was told, by those who listened to the music I created with my muse. It was a most productive time, back when we were alive!]=],
	["0259?"] = [=[Say, Orpheus! I heard what must have been a song of yours, it went something, something, in the blood, you know that one? It was amazing, mate.]=],
	["0261"] = [=[I know that you enjoy this one, my friend!]=],
	["0262"] = [=[This one reminds me of my days alive with my Eurydice...!]=],
	["0263"] = [=[This song had quite a bit of popularity, one time.]=],
	["0267"] = [=[Ah, well, I truly understand. I was reluctant to discuss my long-lost muse, really for quite some time. Well, if you do require some emotional support, know that I likely shall be standing over here...]=],
	["0270"] = [=[But, surely the Queen's mother on Olympus, the great goddess Demeter... surely she would quite like it if she saw her daughter still, from time to time?]=],
	["0271"] = [=[Ah, yes, pomegranate seeds, of course, of course! Though, there is one more subject I don't understand, which is... how you fit into all of this. Were you not trying to escape from here?]=],
	["0272"] = [=[I see! I understand. Well, thank you, then, for clearing all that up. It is a splendid tale, I must say, and every part of it makes sense to me, at last.]=],
	["0268"] = [=[I shall be honored to perform my songs, Your Grace. And, might I add, Your Grace bears many of the striking features of your son? I understand now where he gets his charm.]=],
	["0003"] = [=[I'm sorry I've no will for singing, Zagreus.]=],
	["0004"] = [=[I feel a bit self-conscious seeing as I must refuse to sing...!]=],
	["0005"] = [=[I remain your humble court musician, Zagreus.]=],
	["0006"] = [=[I'm truly pleased to see you, Zagreus.]=],
	["0007"] = [=[Would that I could aid you in some way, my friend.]=],
	["0008"] = [=[It's awfully quiet whilst you're not around. Still rather quiet now!]=],
	["0009"] = [=[Nice speaking with you, Zagreus.]=],
	["0010"] = [=[I'm afraid I haven't much to say on this occasion, Zagreus.]=],
	["0011"] = [=[I hope your day or night, I guess, is going nicely, Zagreus.]=],
	["0012"] = [=[Please do be careful out there, Zagreus.]=],
	["0013"] = [=[I wish I could direct you towards a much more lively court musician.]=],
	["0014"] = [=[Normally I'd offer up a song for such occasions, Zagreus.]=],
	["0015"] = [=[Be strong out there, my friend, OK?]=],
	["0016"] = [=[I'm cheering for you all the way, my friend.]=],
	["0017"] = [=[Good luck to you out in that deadly hellscape, Zagreus.]=],
	["0018"] = [=[Thank you for checking up on me, my friend, although I'm quite all right.]=],
	["0019"] = [=[I'm still fresh out of songs or will to sing them, Zagreus.]=],
	["0020"] = [=[I'd ask if you remember what it's like to feel inspired, my friend, but I don't want to know.]=],
	["0021"] = [=[Oh, hello, Zagreus....]=],
	["0027"] = [=[Wishing you a pleasant day or night as ever, my good friend...!]=],
	["0116"] = [=[May you emerge from all of this unscathed, my friend.]=],
	["0117"] = [=[I trust your neverending toil in the Underworld is proceeding well, my friend?]=],
	["0118"] = [=[I have an optimistic feeling about your next attempt to run away, my friend!]=],
	["0119"] = [=[May you yet find your muse somewhere out there, my friend.]=],
	["0120"] = [=[Each failure brings new opportunities for self-reflection, right, my friend?]=],
	["0121"] = [=[Please keep me well apprised of all of your incredible achievements, Zagreus.]=],
	["0122"] = [=[It lifts my spirits when we briefly interact, my friend.]=],
	["0123"] = [=[I pray the Fates not ruin all your dreams as they did mine!]=],
	["0028"] = [=[I'm in the middle of a song my friend...!]=],
	["0029"] = [=[I'd best get back to singing, Zagreus.]=],
	["0030"] = [=[Let's talk when I'm not singing, Zagreus?]=],
	["0031"] = [=[Hello, my friend, let's get back to my song?]=],
	["0032"] = [=[I'm kind of singing at the moment, Zagreus.]=],
	["0033"] = [=[Terribly sorry I can't speak with you right now.]=],
	["0022"] = [=[I thought I'd lost even the gift of music, Zagreus. So, thanks again for helping find that one for me!]=],
	["0023"] = [=[I must say, it's nice having some music in my life again, and hopefully in yours!]=],
	["0024"] = [=[We all could use a little song from time to time, isn't that so?]=],
	["0025"] = [=[It's nice that I no longer have to live and breathe, and can be focused purely on my song...!]=],
	["0026"] = [=[You rescued me from an eternity of not getting to sing, my friend.]=],
	["0204"] = [=[I hope your day or night is just as splendid as my own, my friend.]=],
	["0205"] = [=[I pray the Fates fulfill your dreams as they did mine!]=],
	["0206"] = [=[Oh, Zagreus, how wonderful to see you once again!]=],
	["0207"] = [=[I was just thinking of you, Zagreus.]=],
	["0208"] = [=[My greetings to my very dearest friend.]=],
	["0101"] = [=[I am in concert as perhaps you see, my friend!]=],
	["0102"] = [=[Begging your pardon, Zagreus, but I'm amid performance at this time!]=],
	["0103"] = [=[I'm quite preoccupied with singing all your praises, Zagreus!]=],
	["0104"] = [=[This hymn is dedicated to your deeds, my friend!]=],
	["0105"] = [=[I cannot talk right now, my friend, for I must sing!]=],
	["0106"] = [=[I trust my music brings some lightness to our gloom-filled times, my friend?]=],
	["0107"] = [=[The tale of your birth is so complex, my friend!]=],
	["0108"] = [=[I ask you please hold your applause until the end!]=],
	["0109"] = [=[To think Lord Dionysus and yourself share such a bond!]=],
	["0110"] = [=[May my performances spread wide your fame, my friend!]=],
	["0111"] = [=[Your parentage need not be secret any longer, Zagreus!]=],
	["0112"] = [=[I shall keep singing of your praises, far and wide!]=],
	["0113"] = [=[You've helped inspire me to song, my friend!]=],
	["0114"] = [=[I must stay focused on my singing, Zagreus.]=],
	["0115"] = [=[I trust my hymn provides some solace to your days or nights?]=],
	["0199"] = [=[My muse writes absolutely wondrous songs, don't you agree?]=],
	["0200"] = [=[Ah, this reminds me so of my Eurydice...]=],
	["0201"] = [=[Would that I were together with her now...]=],
	["0202"] = [=[The songs of my Eurydice are without peer...]=],
	["0203"] = [=[This is a favorite song of mine, and perhaps yours?]=],
	["0034"] = [=[Perhaps a song would be in order at this time?]=],
	["0035"] = [=[Would you be interested in one of my songs?]=],
	["0036"] = [=[What might I do for you, my friend?]=],
	["0037"] = [=[Is there a song which you would like to hear?]=],
	["0038"] = [=[How about a little song, is that all right?]=],
	["0039"] = [=[I am your humble court musician, Zagreus.]=],
	["0040"] = [=[Things might appear a little brighter with a song...!]=],
	["0041"] = [=[OK I like that one.]=],
	["0042"] = [=[Why certainly, of course.]=],
	["0043"] = [=[Why, very well.]=],
	["0044"] = [=[Good, let's begin, my friend!]=],
	["0045"] = [=[All right I like that one!]=],
	["0046"] = [=[I thought you might say that.]=],
	["0047"] = [=[Once more, then, I suppose?]=],
	["0048"] = [=[You like that one, do you?]=],
	["0049"] = [=[I'm happy to oblige you.]=],
	["0050"] = [=[Why, I don't see why not!]=],
	["0060"] = [=[Hello...!]=],
	["0061"] = [=[Hello...]=],
	["0062"] = [=[Hmm.]=],
	["0063"] = [=[Ah.]=],
	["0064"] = [=[Oh, um, hello.]=],
	["0065"] = [=[Hello there.]=],
	["0091"] = [=[Zagreus.]=],
	["0092"] = [=[Zagreus?]=],
	["0093"] = [=[Hello my friend.]=],
	["0094"] = [=[Hello friend.]=],
	["0095"] = [=[Greetings.]=],
	["0177"] = [=[If you insist, my friend.]=],
	["0144"] = [=[Thank you. I shall... I shall.]=],
	["0156"] = [=[Oh, my...]=],
	["0157"] = [=[The famous artistry of Daedalus...]=],
	["0158"] = [=[My music stand...]=],
	["0159"] = [=[By the Fates...]=],
	["0160"] = [=[The gift of song...]=],
	["0161"] = [=[A song returns to me...]=],
	["0162"] = [=[My memory of music stirs...]=],
	["0163"] = [=[Has inspiration struck?]=],
	["0164"] = [=[By my muse...]=],
	["0165"] = [=[Another song...]=],
	["0166"] = [=[A song...]=],
	["0167"] = [=[Another memory...]=],
	["0168"] = [=[I remember...]=],
	["0169"] = [=[How splendid.]=],
	["0170"] = [=[A fine selection.]=],
	["0171"] = [=[Fancy that one, do you?]=],
	["0172"] = [=[Oh, that one.]=],
	["0173"] = [=[That one, then.]=],
	["0174"] = [=[Ah, yes.]=],
	["0175"] = [=[Oh, indeed.]=],
	["0176"] = [=[This makes me think of her.]=],
	["0211"] = [=[I know no other way, my friend.]=],
	["0214"] = [=[Of course, my friend.]=],
	["0220"] = [=[It's almost everything to me, my friend.]=],
	["0235"] = [=[My friend?]=],
	["0236"] = [=[That makes it difficult to sing, my friend.]=],
	["0237"] = [=[Begging your pardon, Zagreus.]=],
	["0238"] = [=[Have I wronged you somehow?]=],
	["0239"] = [=[I resolved never to fight, my friend.]=],
	["0240"] = [=[I fight only through song, my friend.]=],
	["0241"] = [=[Please, Zagreus.]=],
	["0242"] = [=[I am attempting here to sing, my friend!]=],
	["0259"] = [=[I highly doubt it, no.]=],
	["0260"] = [=[I shall give it some thought, I think.]=],
}
