AllDialogue.VoiceLines["Sisyphus"] = {
	["0129"] = [=[Hey, Prince Z. Must look like I'm slacking off with the old boulder, here, but... I was just getting back on my feet. The Fury Sisters don't often leave me be. Where'd they go, anyway? And... what are you doing here?]=],
	["0130"] = [=[Oh I'll let them know, all right, I hear you loud and clear, Your Highness. I'll just go about my business now, and you take care.]=],
	["0131"] = [=[If I may be so bold, Your Highness, I was wondering... what brings you back around this way again? Same story as last time?]=],
	["0133"] = [=[Whew, that is quite an undertaking, Prince. If it wasn't you yourself proposing it, I'd like to call it madness, truth be told. Though you're just mad enough to pull it off! Well hey, I hope you make it. Good fortune out there!]=],
	["0134"] = [=[Hey Prince how goes the old escape plan, any luck?]=],
	["0135"] = [=[Ah, well, keep your chin up. Me, why I quit trying to get out of here a while back, but, if I was a fire-stepping youngster like yourself, perhaps I would have stuck to it.]=],
	["0136"] = [=[Hey, Your Highness, anything the matter, or just passing through? Happy that we get to chat like this of late, of course.]=],
	["0137"] = [=[Hah! Come now, Prince Z., that's just the way I am! Besides, you're not your father, thank the gods! You always seemed a decent lad to me, and if you're saying you want out of here, why, I suppose I can relate, is all.]=],
	["0138"] = [=[Well, it's a bit of a long story, Prince. My time had come, though I just wasn't ready, you might say. Your father thought he had me in his clutches, but then, shoom! I gave him the slip. Your father's henchman, Thanatos, he'll back me up on that.]=],
	["0139"] = [=[Turns out your father doesn't like us mortals cheating death. Eventually they found me, so, now I'm stuck here with my boulder friend. I push old Bouldy up the hill to the beat of the Furies' whips, then he tumbles down, and then we go again.]=],
	["0140"] = [=[You save those sympathies for someone else, Your Highness! I could be Prometheus, spending an eternity having my liver gobbled up, but instead I get to stay in shape, and have these chats with you. Now I'd better get back to it!]=],
	["0141"] = [=[Might surprise you, Highness, I've a bit of royalty in me, myself. Not on your level, mind, but I was very much a king. Though I'll be honest, I... I wasn't much of a good man.]=],
	["0142"] = [=[Well that is awful kind of you to say. Though, I would like to think my punishment here wasn't without warrant. At least I've had a lot of time to think it through!]=],
	["0143"] = [=[Not seen the other Fury Sisters in some time now that you mention it! Just Megaera, the kindly one, and she is quite a handful on her own. I'll keep an eye out for the other two!]=],
	["0144"] = [=[Hey Prince, I heard you showed that Fury Sister the what-for, is that the truth? Might explain why I've been left here to my own devices for a change.]=],
	["0145"] = [=[Now you be careful out there, Highness. The kindly Megaera is out for blood. She kept on groaning 'bout the last exchange between the two of you. You must have showed her good!]=],
	["0146"] = [=[I heard straight from the source the Fury Megaera's been giving you a time, there, hasn't she. Trust me I know the feeling, so, I'm grateful that you're here and that she's not. You give her hell for me next time, won't you?]=],
	["0147"] = [=[Look, Prince, I don't hold grudges, you know that. Push this boulder long as I have, you move past the petty stuff. So, just want you to know, in case you make it out this time, it's been a real pleasure.]=],
	["0148"] = [=[You push old Bouldy here sufficient times, and you might get a different outlook on things, too. With the Furies all preoccupied and with my running into you from time to time, I'm positively doing great lately. I like to take what pleasures I can get!]=],
	["0149"] = [=[Look here, Bouldy, Prince Z. himself has come to visit us!]=],
	["0150"] = [=[Oh, Bouldy's not so bad, I mean, he's a good listener, a good shoulder to lean on, doesn't wield a whip... I rightly can't complain! Good having company down here.]=],
	["0151"] = [=[Say, tell me something, Prince, if you don't mind. How come you're so intent on getting out of here? I mean, what happens when you do?]=],
	["0152"] = [=[I get it, Highness, and I didn't mean to pry, it's just... I can't remember what it's like to want something so bad, you know? Whoever's out there, I hope you find them soon.]=],
	["0153"] = [=[Oh, my, you're really giving that to me, there, Prince? But, I'm just, why would you...?]=],
	["0154"] = [=[Why, Prince, you being serious right now, is that for me?]=],
	["0155"] = [=[Wow, Your Highness, you... you really shouldn't have. Thank you for not forgetting about me.]=],
	["0156"] = [=[I'm really very flattered, Highness! You didn't have to get me anything, I mean, your company's more than enough for me!]=],
	["0157"] = [=[Oh, but this is just too much for me, Your Highness, thank you, really. I don't know how I can ever repay you.]=],
	["0158"] = [=[Wait, really, this, this is for me, you mean it, Prince? I mean, I won't say no, I can't say no to such a thing, so, thank you! Thank you kindly.]=],
	["0159"] = [=[...I'm really rather speechless, Your Highness. I'm just a shade doing my time. I don't deserve your generosity.]=],
	["0160"] = [=[Now hold a moment, Highness, I cannot accept something like this... not without giving back a little something in return, that is!]=],
	["0164"] = [=[Oh, I'm doing very well, thanks, Prince. I'm not afraid of him, I mean, what have I got to lose? Now here, I wanted you to have this.]=],
	["0166"] = [=[Can you believe the nerve of that one, Prince? He's nothing but a blowhard, so, I simply tell him what he wants to hear! He can't stop me from helping you, besides. I'm dead already, what's he going to do?]=],
	["0168"] = [=[Oh I'm just fine, thanks, Prince. That Fury Sister, she is quite a lass, I have to say, and very, very strong. Bet she could push old Bouldy here better than I!]=],
	["0170"] = [=[Never got the boulder to the top, not even once. Always tumbles down right at the very end. Lost count after the nineteen thousandth time or so, but you know what? One of these days, I bet it's going to stick.]=],
	["0171"] = [=[Hey, Prince Z., I heard the strangest rumor, here's the thing, I'll give it to you straight. I have heard you've been consorting both with Megaera the Fury and with that old stiff, Thanatos, can you believe it?]=],
	["0172"] = [=[I... look, I do appreciate the sentiment, Your Highness, I'm just surprised. I thought we shared a common foe in them, is all. What can I say, I hope that someday I can see them how you see them.]=],
	["0173"] = [=[You know, Prince, it's been good not having to see those Fury Sisters quite as much lately. The main one, what's her name, she's on your case now, isn't she.]=],
	["0175"] = [=[Why, I believe you heard just that, Your Highness! Seems the Fates are giving me a break. Although, the Fury Sister did declare that she'll be back to haunting me after she's through with you...]=],
	["0177"] = [=[Prince Z.! Just missed your stern-faced colleague, feel that stillness hanging in the air? Sounds like he won't be checking up on me again anytime soon.]=],
	["0179"] = [=[You know, Prince Z., I'd not expected to run into you again, not after all this time. Something amiss down in the House, or what? Not had much company of late, is all.]=],
	["0180"] = [=[Well I am grateful for it, I and the old boulder there, in turn. I'm used to going lengthy stretches on my own, but having visitors from time to time would do me well!]=],
	["0181"] = [=[Oh, hah! Well, I just think you're in a tough spot lately, Prince. But you'll get through! As for old Bouldy, why, by all means do not hesitate to lay your troubles on him if you like! Dumped all of mine on him a while back.]=],
	["0182"] = [=[That's truly all it takes to make a friend sometimes, indeed, Highness. Now, here.]=],
	["0183"] = [=[He's a good one, all right, isn't he? Though if you've come to such an understanding with old Bouldy there, why, it must mean you've done some growing on your own as well, I think.]=],
	["0184"] = [=[Ah, fortunately I've not seen too much of her, myself, Prince Z. And based on everything that I have seen and heard, I'd like to keep it that way for a while! I hope she doesn't cause you too much trouble there.]=],
	["0185"] = [=[Tisiphone. Why, yes, I have, in fact, Prince Z. She's visited on multiple occasions, truth be told. So she is back, is she?]=],
	["0186"] = [=[Appreciate it, Prince. Of all the Fury Sisters, she's the one I would least care to see. But if she does stop by, you know, that's how it goes.]=],
	["0187"] = [=[Oh, well, you know! I have acquaintances amongst the locals here, try to be neighborly with everyone is all. It's not just Bouldy and myself as you can see. Sometimes I come across things that'd be better off in other hands than mine.]=],
	["0188"] = [=[Say, that's my Shattered Shackle on your person, right, Prince Z.? I'd recognize that clunky thing from anywhere. It serving you all right?]=],
	["0189"] = [=[Bit of an odd story, that. Involved a well-timed accident with the old boulder there. Though, I'd best not get into it so that you're not accomplice to that little crime. Surely you understand?]=],
	["0190"] = [=[My Shattered Shackle's practically like new, there, Prince! Minus the part where it's still broken, and all that. Nice work!]=],
	["0191"] = [=[Hahahahah! Absolutely not, though truly I appreciate the sentiment. I'd rather have a look at the old boulder there than a symbol of the time I first got stuck here, when I wasn't doing quite as well.]=],
	["0192"] = [=[Why, Prince, is this...? It is...! I've not so much as seen a bottle of it, much less sampled it, thank you so much! Although, with all respect, I cannot rightfully accept such a fine gift. Unless...]=],
	["0193"] = [=[This, Highness, is a little friend of mine kept tucked away in Bouldy's care. Wherever you'll be going next, he'll make a worthy traveling companion. And when he's with you, Bouldy and I... we'll be with you in spirit, too.]=],
	["0195"] = [=[Well, Your Highness, I am honored very much indeed, and having you amongst my list of friends makes it perhaps the greatest such a list a fellow such as I has ever had. Isn't that right, Bouldy?]=],
	["0196"] = [=[NPC_SisyphusAndBouldy_01]=],
	["0197"] = [=[Prince Z., it seems you've brought my little Shady back to visit me! How very kind. And I can tell he's in good care of late.]=],
	["0198"] = [=[All due respect, Highness, but I've the best friend anyone can ask for to my right just there. And as for little Shady, he was more inclined than I to see the farthest reaches of the Underworld. Safe travels to you both!]=],
	["0199"] = [=[Oh, come now, Prince, do Bouldy and I look like we could use your charity? We're planning to stay put within this chamber for a while. It's hardly a predicament, I'd say.]=],
	["0200"] = [=[Ah, yes, the Fury Sisters, well. I wouldn't mind seeing them more infrequently now that you mention it, but either way! So don't you even worry about me. Now, here.]=],
	["0201"] = [=[Oh! Indeed, then, does this mean, Prince, then... the Fury Sisters, they won't come around as often anymore?]=],
	["0202"] = [=[You're much too kind to this old soul, Prince Z. The thing is, this is home. For me and Bouldy, it is what it is. Though, knowing that the Furies won't be visiting with quite their former regularity, that is a load off. Heavier than Bouldy, there.]=],
	["0203"] = [=[Is that so odd, Highness? Don't see myself lugging old Bouldy out of here, besides! And if I were to leave, why, we would not be having these exchanges now and then. I happen to enjoy them quite a bit! Now, here you go, and thank you, very much.]=],
	["0204"] = [=[Look, Prince, it's not for me to judge you, or your friends. The Fury Sisters, Master Thanatos... we got off on the wrong foot, you could say. My fault, entirely. I'd sooner make sure that our correspondence here doesn't make those relationships more difficult.]=],
	["0205"] = [=[Certainly, Highness. And who knows? Perhaps as you spend more time together, some of your finer qualities will rub off on those two!]=],
	["0411"] = [=[Well, Prince, I told you that we'd be with you in spirit, didn't I? It's not just Shady's power, I suppose, nor is it Bouldy's or my hidden strength. It's testament to our companionship, is all. You gods are capable of anything!]=],
	["0413"] = [=[What? You mean that you've never touched the stuff yourself? You've much more self control than I have, there. Perhaps someday we'll have a chance to share some between us!]=],
	["0418"] = [=[Prince, you've been gone for quite a while, why... I heard-tell you made it all the way outside! And I believed it for a while there, yet here you are. What happened, might I ask?]=],
	["0419"] = [=[Well, I am certainly delighted to hear that! So long as you achieved what you set out to do. But, what brings you back again this way? More than a social visit I presume.]=],
	["0420"] = [=[Going to try and make it out of here again and again, is it? Well they say repetition is the key to mastery, Prince Z. Now here, I'll send you on your way.]=],
	["0423"] = [=[Prince Z., my understanding is the Queen herself is back, is that correct? Moreover, I have heard a truly fascinating rumor about her...]=],
	["0424"] = [=[That's wonderful to hear. I'd always heard good things about that one. No wonder such a quality runs in the family.]=],
	["0425"] = [=[Must say, Prince Z., the free life sure does have its perks down here! This place really isn't as bad as it's cracked up to be.]=],
	["0426"] = [=[Well, it used to be I'd have to start heaving Bouldy there at any point, if the Fury Sisters decided to show up. But now? I just get to relax, chat a bit with the other shades, and give you one of these when you're in the area!]=],
	["0427"] = [=[Ah, there you are, Prince! I was just thinking about how grateful I am that you got me out of that contract with your father. It's been a real weight off my shoulders, truth be told.]=],
	["0428"] = [=[And I could say the same to you! Look, I know you were concerned for my wellbeing. Now you don't have to be. And I'll still be around to help you out. Good feeling, isn't it?]=],
	["0429"] = [=[You must have seen everything there is to see here in your father's Underworld, haven't you, Prince? I figure that there isn't any place nicer than this!]=],
	["0430"] = [=[I'll take what's coming to me right here, thank you very much. You're the wayfaring sort, but my wayfaring days are over. It's hard to explain, but... this is a much-needed fresh start for me.]=],
	["0431"] = [=[Well, ah-hah, the thing is that I wasn't, Highness. And that's not modesty from me, all right? All behind me, now. And I'd appreciate it if we left it at that.]=],
	["0432"] = [=[It's more like... this is where I belong. Where my path has taken me, you know? Here in the Underworld, you can't entirely escape your past... and yet, it's like you get another life to live. With all the wisdom that you picked up along the way.]=],
	["0433"] = [=[Word is that the most beautiful music's been heard up in Asphodel, lately, Prince! From the sound of it, why... I think that has got to be Eurydice and Orpheus!]=],
	["0434"] = [=[Oh, I've more than heard of them! I'm sure you know how Orpheus once ventured all the way down here, after Eurydice passed on. I'll never forget his song! Even the Fury Sisters gave me a break, they were so captivated by it, then. Ah, good times. For me, at least!]=],
	["0435"] = [=[I will have you know, Prince, that your visits here have become a very important part of my routine!]=],
	["0436"] = [=[Why, the routine of looking forward, of course! I try to appreciate the moment as much as anybody, but you know? It's always nice having something to look forward to. So, see you next time, then?]=],
	["0437"] = [=[You know, Prince Z., you really have a look about you that you know exactly where you're going, as of late. I used to think you weren't near as comfortable in your own skin.]=],
	["0438"] = [=[Nor did we have much opportunity to chat back then, but hey! You always struck me as a decent sort. Wasn't accustomed to your father's henchpeople greeting me with a smile.]=],
	["0439"] = [=[Hey, Your Highness, good, old Bouldy there had several things he wanted to tell you.]=],
	["0440"] = [=[Thank you for listening to him! With all that said, I think I've got something for you right here.]=],
	["0441"] = [=[Hey Prince, ah, so... you do know Bouldy's just a plain old rock with a few lines chiseled into him, resembling a face, don't you? Chiseled into it, I mean. Just so you don't get the wrong idea...]=],
	["0442"] = [=[Hahahaha, no. Was just a jest, there, at Bouldy's expense. Look at him! He gets so annoyed when I call him a plain old rock like that. But then he calls me an old lazy lump, and then we're even for a while.]=],
	["0443"] = [=[How goes it with old Master Thanatos of late, Prince Z.? Is he at least less stern with you than with the poor mortals he's sent to take in here?]=],
	["0444"] = [=[That's good, I guess! Always appreciated that he ultimately took me in, rather than having to show up here through much more sudden, much more painful means. Didn't stop me from trying to avoid the trip, of course.]=],
	["0445"] = [=[Word is you've caused quite the hubbub in Elysium, Prince Z.! Making the champion up there really work for it, I hear?]=],
	["0446"] = [=[I bet he'd like you better if you were a regular pushover! Ah, well, he'll learn, I'm sure.]=],
	["0469"] = [=[So, how do you like the surface, hey, Prince Z.? Now that you've finally had a chance to see it for yourself. Not too bad, I hope?]=],
	["0470"] = [=[Oh, you know. I still have almost everything that matters, and the rest? It makes for precious memories I didn't have up there.]=],
	["0471"] = [=[So, all this time, Prince, when you were battling up to the surface, and all that... you were searching for her, weren't you? The Queen?]=],
	["0473"] = [=[Just one thing I don't understand, Prince Z., if you'll indulge me for a moment, here. If everything is all right for you at the House, then... why is it you're fighting to the surface, still?]=],
	["0474"] = [=[Sure, that makes sense! Well, from a certain point of view. Escape over and over to prove it can't be done! I like that. Well, let's both of us keep at it, then!]=],
	["0475"] = [=[Not working yourself too hard of late, are you, Prince Z.? Remembering to take some breaks from time to time, and all?]=],
	["0476"] = [=[Well, it was work, you know? Even your Father has to work. Of course, I've since retired! But it seems you and he like to keep yourselves occupied. Whatever makes you feel content.]=],
	["0477"] = [=[Ah, look at what the Prince has brought for us, Bouldy! Perhaps someday we'll have a chance to share some between us!]=],
	["0478"] = [=[Well, just the one time, briefly, when your father decided to put me here. And, you have my word, of course. About the... surface stuff.]=],
	["0178"] = [=[Oh, I believe it, Highness. I should think that bringing death must be a lonely job. Perhaps he ought to try pushing a boulder sometime!]=],
	["0002"] = [=[Good to see you in one piece, Prince Z.!]=],
	["0003"] = [=[Life treating you all right, I take it, Prince?]=],
	["0004"] = [=[Oh I'm hanging in there, thanks for asking, Prince!]=],
	["0005"] = [=[You'll make it out of here, I've no doubt about it!]=],
	["0006"] = [=[Nice of you to drop in for a bit!]=],
	["0007"] = [=[You are a sight for sore eyes, Prince!]=],
	["0008"] = [=[Now you be careful out there, won't you, Prince?]=],
	["0009"] = [=[You give them hell for me, all right, Prince Z.?]=],
	["0010"] = [=[Go get them for me, Prince!]=],
	["0011"] = [=[Got just the thing for you here, Prince!]=],
	["0012"] = [=[It's always good to see you, Prince!]=],
	["0013"] = [=[You keep your chin up, Prince!]=],
	["0014"] = [=[Keep fighting the good fight, there, Prince!]=],
	["0015"] = [=[Hey you take care, you hear me, Prince?]=],
	["0016"] = [=[Let's both of us keep going, that a deal?]=],
	["0017"] = [=[It's good of you to visit me like this!]=],
	["0018"] = [=[Hope everything's been well enough of late.]=],
	["0019"] = [=[You watch your step out there, all right, Prince Z.?]=],
	["0020"] = [=[Hullo Highness, you're looking well enough!]=],
	["0021"] = [=[Hey, Your Highness, how goes it, how is everything?]=],
	["0022"] = [=[I have to say it's good to see a friendly face!]=],
	["0023"] = [=[Always a pleasure, Highness, you take care out there.]=],
	["0024"] = [=[Here's my best friend in all the Underworld, how goes it, Prince?]=],
	["0025"] = [=[Glad you made it all this way, Prince Z.]=],
	["0334"] = [=[Think I've got just the thing for you right here, Highness!]=],
	["0335"] = [=[A brief hello from time to time does wonders, don't you think, Prince Z.?]=],
	["0336"] = [=[Much as I like the company of Bouldy there, you're always welcome, Prince!]=],
	["0337"] = [=[Stop by whenever you're around these parts, all right, Prince Z.?]=],
	["0338"] = [=[I know it isn't much, Highness, but I do hope this helps!]=],
	["0339"] = [=[Here's something courtesy of me and Bouldy, Prince!]=],
	["0340"] = [=[How about a little bit of help as you keep on your journey, Prince?]=],
	["0341"] = [=[Let's see if we might make your going slightly easier, there, Prince!]=],
	["0342"] = [=[Should have something that ought to come in handy for you, Prince!]=],
	["0343"] = [=[No need for these, so take one off my hands, won't you, Prince Z.?]=],
	["0344"] = [=[Bouldy and I have got the usual for you right here, Your Highness.]=],
	["0345"] = [=[Highness, please take one of these and go!]=],
	["0351"] = [=[All's well out here in Tartarus, Prince Z.! What will it be?]=],
	["0352"] = [=[Bouldy and I got our usual selection here, Highness!]=],
	["0456"] = [=[Don't let me keep you, Prince, I know you've plenty of important business here.]=],
	["0457"] = [=[Before you go, Prince Z., a little souvenir from your fine stay in Tartarus.]=],
	["0458"] = [=[Don't do anything I wouldn't do out there, you hear me, Prince?]=],
	["0459"] = [=[You're looking good and ready for whatever lies ahead up there, Prince Z.!]=],
	["0460"] = [=[You know approximately where to find me if you happen to be in the area again, Prince Z.!]=],
	["0461"] = [=[Everything's fine as ever here, Prince Z., so you go on ahead, and don't look back!]=],
	["0462"] = [=[I have a feeling you are going to make it all the way topside this time, Highness!]=],
	["0032"] = [=[Need a little pick-me-up perhaps?]=],
	["0346"] = [=[Bouldy and I will always be here in your time of need, Prince Z.!]=],
	["0347"] = [=[Bouldy says whatever we can do to help, we'll do it, Prince!]=],
	["0348"] = [=[In case words of encouragement are not enough, have one of these here, Prince!]=],
	["0349"] = [=[Let's get you on your way, Prince Z., and in good spirits, too!]=],
	["0350"] = [=[Don't you worry, Highness, we have got you covered here!]=],
	["0353"] = [=[Told old Bouldy here you'd probably be back if only to say hi!]=],
	["0354"] = [=[Hey Prince, Bouldy and I will not be needing these, but maybe they can help!]=],
	["0355"] = [=[Just do the best you can, if you don't mind me saying so, Prince Z.!]=],
	["0453"] = [=[Speaking for myself and Bouldy there, we're always at your service, Prince.]=],
	["0454"] = [=[You get all the way up to the top and do whatever it is needs getting done, Highness!]=],
	["0455"] = [=[I know Bouldy believes in you every bit as much as I do, Prince!]=],

	["0167"] = [=[Sounds good, sounds good, Madam, that's more than equitable really, I'll hold you to that! Be seeing you around!]=],
	["0169"] = [=[I appreciate your vigilance, Madam, and surely I'll be getting Bouldy up this very hill in no time flat, despite the fact that I have never once achieved this!]=],
	["0174"] = [=[Entirely makes sense to me, Madam, and rest assured that Bouldy, erm, that is to say this boulder here, that I will push it regularly, moving forward, same as ever! Now good-bye!]=],
	["0163"] = [=[Why, absolutely, Master Thanatos, I wouldn't think of it! My mind is fully occupied with all the latest boulder-pushing strategies, besides.]=],
	["0176"] = [=[Well, that's just it, Master Thanatos. I never was terribly fearful of you gods, if you'll forgive my saying so. Far as I can tell, all of you seem to have your struggles much like mortals do. A fear of death aside.]=],
	["0026"] = [=[Bouldy and I, we're proud to be of service, Your Highness!]=],
	["0027"] = [=[What'll it be?]=],
	["0028"] = [=[Something I can do for you?]=],
	["0029"] = [=[Let's get you on your way!]=],
	["0030"] = [=[How can I help?]=],
	["0031"] = [=[I interest you in one of these?]=],
	["0033"] = [=[Think I can be of service!]=],
	["0034"] = [=[Go on and take your pick!]=],
	["0035"] = [=[What can I do for you?]=],
	["0036"] = [=[I got you covered!]=],
	["0037"] = [=[Here's what I've got.]=],
	["0038"] = [=[Sure thing!]=],
	["0039"] = [=[You got it.]=],
	["0040"] = [=[Say no more!]=],
	["0041"] = [=[Easy does it!]=],
	["0042"] = [=[Good choice!]=],
	["0043"] = [=[A fine selection there!]=],
	["0044"] = [=[It's all yours!]=],
	["0045"] = [=[Sure, here you go!]=],
	["0046"] = [=[Good idea!]=],
	["0047"] = [=[Makes sense to me!]=],
	["0048"] = [=[Most excellent!]=],
	["0049"] = [=[Not to worry!]=],
	["0050"] = [=[That who I think it is...?]=],
	["0051"] = [=[Ahoy!]=],
	["0052"] = [=[Ahoy there!]=],
	["0053"] = [=[Look who!]=],
	["0054"] = [=[Hullo!]=],
	["0055"] = [=[Hullo, hullo!]=],
	["0056"] = [=[Just on a little break!]=],
	["0057"] = [=[Perfect timing!]=],
	["0058"] = [=[Your Highness!]=],
	["0059"] = [=[Well, well!]=],
	["0060"] = [=[Aren't you a sight!]=],
	["0061"] = [=[Prince Z.!]=],
	["0062"] = [=[Hey, hey!]=],
	["0063"] = [=[Good morning or whenever!]=],
	["0064"] = [=[Uh, Prince?]=],
	["0065"] = [=[Nice try, there!]=],
	["0066"] = [=[No use in that.]=],
	["0067"] = [=[Already dead here, Prince.]=],
	["0068"] = [=[Don't bother, Prince.]=],
	["0069"] = [=[Come on, now.]=],
	["0070"] = [=[Oh come now.]=],
	["0071"] = [=[Why bother.]=],
	["0072"] = [=[Try all you like!]=],
	["0073"] = [=[Very funny, Prince.]=],
	["0074"] = [=[Oof, got me good there!]=],
	["0075"] = [=[Nope, can't feel a thing.]=],
	["0076"] = [=[That's it, let all out.]=],
	["0077"] = [=[Could use a little help here...!]=],
	["0078"] = [=[Hey lend a hand would you?]=],
	["0079"] = [=[I'm in a bit of trouble Prince...!]=],
	["0080"] = [=[Could use a hand I think...!]=],
	["0081"] = [=[Um, hello, Prince...!]=],
	["0082"] = [=[Nice day we're having, Prince...!]=],
	["0083"] = [=[Um, hello, how's it going?]=],
	["0084"] = [=[Mind lending me a hand here?]=],
	["0085"] = [=[Hate to bother you, but, uh...]=],
	["0086"] = [=[Oh hi there Prince...!]=],
	["0087"] = [=[A little help here?]=],
	["0088"] = [=[Erm, Prince...?]=],
	["0089"] = [=[Got a little situation, Prince!]=],
	["0090"] = [=[Another day in Tartarus!]=],
	["0091"] = [=[Aren't you a sight!]=],
	["0092"] = [=[Prince Z.!]=],
	["0093"] = [=[Good morning or whenever!]=],
	["0094"] = [=[Your Highness!]=],
	["0095"] = [=[Thank you, Prince.]=],
	["0096"] = [=[Thank you.]=],
	["0097"] = [=[I owe you one.]=],
	["0098"] = [=[Just in the nick of time!]=],
	["0099"] = [=[Whew!]=],
	["0100"] = [=[Whew.]=],
	["0101"] = [=[That's a relief.]=],
	["0102"] = [=[Peace and quiet!]=],
	["0103"] = [=[You sure showed them!]=],
	["0104"] = [=[They sure got theirs!]=],
	["0105"] = [=[You got them!]=],
	["0106"] = [=[Much better!]=],
	["0107"] = [=[That's more like it!]=],
	["0108"] = [=[Thought they'd never leave!]=],
	["0109"] = [=[I'm in your debt.]=],
	["0110"] = [=[Am I glad you showed up.]=],
	["0111"] = [=[Take care out there!]=],
	["0112"] = [=[Good luck out there!]=],
	["0113"] = [=[Godspeed and all!]=],
	["0114"] = [=[Take care of yourself!]=],
	["0115"] = [=[Go get them, Prince!]=],
	["0116"] = [=[Farewell, Highness!]=],
	["0117"] = [=[Safe travels!]=],
	["0118"] = [=[Bye now!]=],
	["0119"] = [=[You can do this!]=],
	["0120"] = [=[So long for now!]=],
	["0121"] = [=[Keep going, Prince!]=],
	["0122"] = [=[Well you take care!]=],
	["0123"] = [=[Bye now!]=],
	["0124"] = [=[You can do it!]=],
	["0125"] = [=[You got this, Prince!]=],
	["0126"] = [=[Farewell, then!]=],
	["0127"] = [=[All right, bye!]=],
	["0128"] = [=[Careful out there!]=],
	["0132"] = [=[Hoh that is quite an undertaking, Prince. If it wasn't you yourself proposing it, I'd like to call it madness, truth be told. Though you're just mad enough to pull it off! Hey, hold a moment, here -- I've got something could be of some help.]=],
	["0161"] = [=[All right, Prince Z., if you're to be so generous with me, I wanted to make sure that I could get you back. Not centuries from now, but right away. So, take this, with my compliments.]=],
	["0162"] = [=[Ohh, now this is going to get me through at least another century of boulder-pushing I should say! And I have got something for you as well.]=],
	["0206"] = [=[Bouldy, look who!]=],
	["0207"] = [=[Hullo, Your Highness!]=],
	["0208"] = [=[You're back, welcome!]=],
	["0209"] = [=[He's back again, Bouldy!]=],
	["0210"] = [=[Good to see you!]=],
	["0211"] = [=[Caught me on a break again!]=],
	["0212"] = [=[Hullo, Prince Z.!]=],
	["0213"] = [=[How nice to see you, Prince!]=],
	["0214"] = [=[It's him, Bouldy!]=],
	["0215"] = [=[Well if it isn't you!]=],
	["0216"] = [=[Ahoy, what's new of late?]=],
	["0217"] = [=[The Prince returns!]=],
	["0218"] = [=[What a surprise!]=],
	["0219"] = [=[Why, look who's here, Bouldy!]=],
	["0220"] = [=[That I can do!]=],
	["0221"] = [=[Got just the thing!]=],
	["0222"] = [=[I got you covered, Prince!]=],
	["0223"] = [=[Certainly, Highness!]=],
	["0224"] = [=[Sure thing, Prince Z.!]=],
	["0225"] = [=[My pleasure, Prince!]=],
	["0226"] = [=[No worries whatsoever!]=],
	["0227"] = [=[Think I can do that, Prince!]=],
	["0228"] = [=[Got that right here, Prince Z.!]=],
	["0229"] = [=[Then here you go!]=],
	["0230"] = [=[Ah, certainly, Prince Z.!]=],
	["0231"] = [=[Here you are!]=],
	["0232"] = [=[Hah, good one, Prince!]=],
	["0233"] = [=[Augh, you got me, Highness!]=],
	["0234"] = [=[Oh, please, have mercy and all that!]=],
	["0235"] = [=[That your best shot, Prince Z.?]=],
	["0236"] = [=[Now don't get frustrated all right?]=],
	["0237"] = [=[You getting ready for the road ahead?]=],
	["0238"] = [=[Nice shot there, Prince!]=],
	["0239"] = [=[Augh, I'm hit!]=],
	["0240"] = [=[Wow you are strong Prince Z.!]=],
	["0241"] = [=[Whew, most impressive, Prince!]=],
	["0242"] = [=[See you again, all right?]=],
	["0243"] = [=[Do tell the Furies I said hi!]=],
	["0244"] = [=[You have this, Prince!]=],
	["0245"] = [=[Stop by again sometime!]=],
	["0246"] = [=[Careful out there, all right?]=],
	["0247"] = [=[May you get out of here this time, Highness!]=],
	["0248"] = [=[Always a pleasure, Prince!]=],
	["0249"] = [=[So long, Highness!]=],
	["0250"] = [=[Think he'll go all the way this time, Bouldy?]=],
	["0251"] = [=[Keep fighting, Highness!]=],
	["0252"] = [=[Thanks for stopping by!]=],
	["0253"] = [=[Until next time, all right?]=],
	["0254"] = [=[Pick on somebody your own size, Prince!]=],
	["0255"] = [=[That's one fight you aren't going to win!]=],
	["0256"] = [=[Takes more than that to budge old Bouldy, Prince!]=],
	["0257"] = [=[Sure is heavy, isn't he!]=],
	["0258"] = [=[Bouldy can take whatever you dish out!]=],
	["0259"] = [=[Now there's no need for that here, Prince.]=],
	["0260"] = [=[Try all you like, there, Prince!]=],
	["0261"] = [=[Hey that's my friend, Prince Z.]=],
	["0262"] = [=[No hurting Bouldy, Prince.]=],
	["0263"] = [=[That's one tough rock you're messing with.]=],
	["0264"] = [=[Don't hurt yourself, all right?]=],
	["0265"] = [=[Come now, Highness!]=],
	["0266"] = [=[Why, your Highness?]=],
	["0267"] = [=[Oh what did Bouldy ever do to you?]=],
	["0268"] = [=[Look out below!]=],
	["0269"] = [=[Heads up!]=],
	["0270"] = [=[Prince Z.!]=],
	["0271"] = [=[Hang on, Prince!]=],
	["0272"] = [=[Gangway!!]=],
	["0273"] = [=[Bouldy!]=],
	["0274"] = [=[Here we go!]=],
	["0275"] = [=[Here goes!]=],
	["0276"] = [=[Coming through!]=],
	["0277"] = [=[Whoopsie!]=],
	["0278"] = [=[Ahoy, Prince!]=],
	["0279"] = [=[Ahoy!!]=],
	["0280"] = [=[Aaand, here!]=],
	["0281"] = [=[We got you, Highness!]=],
	["0282"] = [=[Happy to help!]=],
	["0283"] = [=[Coming right up!]=],
	["0284"] = [=[Here comes Bouldy!]=],
	["0285"] = [=[Bouldy, now!]=],
	["0286"] = [=[Hah, haaah!!]=],
	["0287"] = [=[Begging your pardon!!]=],
	["0288"] = [=[Hullo there Prince!!]=],
	["0289"] = [=[Got you covered!!]=],
	["0290"] = [=[Pardon, Madam!!]=],
	["0291"] = [=[Payback time, Bouldy!]=],
	["0292"] = [=[It's the Fury Sisters!]=],
	["0293"] = [=[Ahoy, Madam!!]=],
	["0294"] = [=[Get her, Bouldy!]=],
	["0295"] = [=[Let's get the drop on her!]=],
	["0296"] = [=[It's Master Thanatos!]=],
	["0297"] = [=[Ahoy there, Master Thanatos!]=],
	["0298"] = [=[How goes it, Master Thanatos?!]=],
	["0299"] = [=[How's business, Master Thanatos?]=],
	["0300"] = [=[Don't mind me, Master Thanatos!]=],
	["0301"] = [=[Why if it isn't Master Thanatos!]=],
	["0302"] = [=[Why, Master Hades, sir!]=],
	["0303"] = [=[Ahoy Lord Hades sir!!]=],
	["0304"] = [=[Beg pardon Master Hades sir!]=],
	["0305"] = [=[Lord Hades himself!!]=],
	["0306"] = [=[Your Highnesses!!]=],
	["0307"] = [=[Now you two get along!]=],
	["0308"] = [=[We're here for you, Highness!]=],
	["0309"] = [=[Prince Z., we're back!]=],
	["0310"] = [=[Get them again, Bouldy!]=],
	["0311"] = [=[We got you, Prince!]=],
	["0312"] = [=[Right here beside you, Prince!]=],
	["0313"] = [=[Time for another go, Bouldy!]=],
	["0314"] = [=[Bouldy coming through!]=],
	["0315"] = [=[Once more, Bouldy!]=],
	["0316"] = [=[Whoops!]=],
	["0317"] = [=[Sorry!]=],
	["0318"] = [=[My fault!]=],
	["0319"] = [=[Bouldy!!]=],
	["0320"] = [=[Ah well!]=],
	["0321"] = [=[My mistake!]=],
	["0322"] = [=[Missed!]=],
	["0323"] = [=[We missed?]=],
	["0324"] = [=[Not here, Prince!]=],
	["0325"] = [=[Haha, nice try there!]=],
	["0326"] = [=[Fraid not, Prince Z.]=],
	["0327"] = [=[What good would that do here?]=],
	["0328"] = [=[Oh come now.]=],
	["0329"] = [=[Already here to help!]=],
	["0330"] = [=[Call on us almost anytime!]=],
	["0331"] = [=[We're right here, Prince!]=],
	["0332"] = [=[Come now, Highness!]=],
	["0333"] = [=[Call us when you need us!]=],
	["0356"] = [=[Bouldy is much obliged!]=],
	["0357"] = [=[Thanks on behalf of Bouldy there!]=],
	["0358"] = [=[Look how happy Bouldy is!]=],
	["0359"] = [=[That's one good rock, isn't he, Prince!]=],
	["0360"] = [=[You've Bouldy's favor, Prince!]=],
	["0361"] = [=[I think he likes you!]=],
	["0362"] = [=[Bouldy is grateful.]=],
	["0363"] = [=[Your offering has been accepted, Prince!]=],
	["0364"] = [=[I'm sure he's grateful, Prince.]=],
	["0365"] = [=[That's good of you, Prince Z.!]=],
	["0366"] = [=[Bouldy has got you covered!]=],
	["0367"] = [=[See that, Bouldy?]=],
	["0368"] = [=[Think Bouldy's warming up to you!]=],
	["0369"] = [=[Bouldy's a good listener isn't he!]=],
	["0370"] = [=[You have been blessed by Bouldy!]=],
	["0371"] = [=[You show those dusty pots!]=],
	["0372"] = [=[Nice shot, Prince Z.!]=],
	["0373"] = [=[That sound never gets old!]=],
	["0374"] = [=[Thank you for picking up a bit!]=],
	["0375"] = [=[They keep replacing those.]=],
	["0376"] = [=[Nice shot, Prince Z.!]=],
	["0377"] = [=[I'm glad that wasn't me!]=],
	["0378"] = [=[Break all the pots you like!]=],
	["0379"] = [=[Fraid those are empty, Prince!]=],
	["0380"] = [=[Don't bother with those, Prince.]=],
	["0381"] = [=[Chased them away you did!]=],
	["0382"] = [=[Those shades always come back.]=],
	["0383"] = [=[Oh those shades aren't so bad.]=],
	["0384"] = [=[Why trouble them, Prince Z.?]=],
	["0385"] = [=[No need for that here, Prince.]=],
	["0386"] = [=[They'll just come back next time.]=],
	["0387"] = [=[Those shades are stuck here, Prince.]=],
	["0388"] = [=[Why shoo those shades away?]=],
	["0389"] = [=[Oh, I'll just stash that one away, then, Prince!]=],
	["0390"] = [=[Appreciated, Highness, rest assured.]=],
	["0391"] = [=[Is that for me, Prince Z.? Well then, all right!]=],
	["0392"] = [=[I'll take that off your hands if you insist, Highness.]=],
	["0393"] = [=[I've not much need of that, but I can take it, Prince!]=],
	["0394"] = [=[Come now, Highness, you really shouldn't have.]=],
	["0395"] = [=[Please don't take this the wrong way, Prince, but I cannot accept something like this.]=],
	["0396"] = [=[Apologies, Prince Z., but I've no need of that. You'd best hang onto it.]=],
	["0397"] = [=[Afraid I have no need for that, Highness, though I appreciate the gesture there!]=],
	["0398"] = [=[Thank you, Prince Z., though I've no use for this right now.]=],
	["0399"] = [=[Your Highness, I was wondering if you might hear me out.]=],
	["0400"] = [=[Prince Z., I've a small favor I would ask of you if you don't mind.]=],
	["0401"] = [=[Wanted to ask you something here, Highness.]=],
	["0402"] = [=[Quick request if you've a moment for us, Prince.]=],
	["0403"] = [=[<Laughter>]=],
	["0404"] = [=[<Laughter>]=],
	["0405"] = [=[Hrm.]=],
	["0406"] = [=[Eh.]=],
	["0407"] = [=[<Scoff>]=],
	["0408"] = [=[Wha?]=],
	["0409"] = [=[Huh.]=],
	["0410"] = [=[Hmm.]=],
	["0414"] = [=[Ohh, this is the choicest stuff that you've procured, Prince Z.!]=],
	["0415"] = [=[Is that for me really, Highness? You know I absolutely love the stuff?]=],
	["0416"] = [=[Augh, look at what the Prince has brought for us, Bouldy!]=],
	["0417"] = [=[On behalf of Bouldy and myself, we're very grateful for your gesture here.]=],
	["0447"] = [=[Oh, Charon!]=],
	["0448"] = [=[It's Charon!]=],
	["0449"] = [=[Well if it isn't Charon!]=],
	["0450"] = [=[Here's something, Charon!]=],
	["0451"] = [=[Flatten him, Bouldy!]=],
	["0452"] = [=[Here's the fee, Charon!]=],
	["0463"] = [=[Bouldy appreciated that!]=],
	["0464"] = [=[Oh, look how happy Bouldy is!]=],
	["0465"] = [=[You're most gracious, Prince Z.]=],
	["0466"] = [=[You see that, Bouldy?]=],
	["0467"] = [=[You two have a real thing going!]=],
	["0468"] = [=[Bouldy's got your back.]=],
}
