AllDialogue.VoiceLines["Skelly"] = {
	["0003"] = [=[You getting pretty strong, I'll give you that, boyo. Strong enough to smack a guy like me right up against the wall and I'd go straight to pieces, boom! You just remember, when you're duking it out, the walls are your friend!]=],
	["0006"] = [=[Not a chance, boyo, I'm paid to take it not to dish it out! Now give it to me!!]=],
	["0026"] = [=[Less yakking, more smacking, boyo, now come on!]=],
	["0027"] = [=[Less chatter, more batter, boyo, hit me already!]=],
	["0028"] = [=[Less talking, more socking, here, pal!]=],
	["0029"] = [=[Come on, boyo, less gabbing, more stabbing over here!]=],
	["0030"] = [=[Less prattle, more battle, boyo, give me all you got!]=],
	["0031"] = [=[Can't break these bones, pal, what you just try it!]=],
	["0032"] = [=[You want another a piece of this, or what?]=],
	["0033"] = [=[Enough with the small talk, boyo, hit me, go on!]=],
	["0034"] = [=[Trying to bore me to death with all this chit-chat, pal?]=],
	["0035"] = [=[This look like a shoulder to cry on to you, boyo?]=],
	["0036"] = [=[Let me have it already, boyo, no holding back!]=],
	["0037"] = [=[Let's see what you can do in terms of hitting me, pal!]=],
	["0038"] = [=[You could be hitting me right now, boyo!]=],
	["0039"] = [=[Sure could go for somebody just whaling away on me right now.]=],
	["0040"] = [=[What's the matter, you gone soft or something, pal?]=],
	["0041"] = [=[You going to hit me over here, or what?]=],
	["0042"] = [=[Go on, boyo, give me your best shot, it's my job!]=],
	["0043"] = [=[Sure could use a good smack in the jaw from you right about now!]=],
	["0044"] = [=[You want to fight me, boyo, well hop to it, stat!]=],
	["0045"] = [=[What do I look like, pal, some kind of conversationalist?]=],
	["0046"] = [=[Our relationship, boyo, requires no exchange of words!]=],
	["0115"] = [=[Whoa-hoh, you being serious here, pal? You brought that all this way, for little old me?! That's real nice of you!]=],
	["0116"] = [=[Whoaaaa, now get a load of what you got there, boyo! Wait, really, that's for me? Or you just pulling my leg?]=],
	["0117"] = [=[Heeey now that's what I'm talking about, thanks, boyo! Won't forget you doing me a solid like this, cross my heart!!]=],
	["0118"] = [=[Oh look here, pal, I can't just keep accepting these from you! Not when they're paying me already, I got standards to uphold, you know?]=],
	["0119"] = [=[Haaah, you're kidding, what? Sometimes, boyo, you make me feel alive again, you know that? Being honest with you here, I'm grateful, really.]=],
	["0120"] = [=[For me, pal? Awful nice of you, just awful nice, but guess what, I got this for you! Tit for tat, you understand, a deal's a deal!]=],
	["0160"] = [=[Oh-hoh, I'm not about to rat my sources, pal! Just try and beat it out of me!]=],
	["0161"] = [=[Hey, you're getting pretty strong, there, pal! Though, I am being paid to tell you that! But not being paid to not tell you that last part...]=],
	["0162"] = [=[That, pal, is nobody's business but my own! Besides, it's impolite discussing money all the time! Now back to beating me to powder!]=],
	["0165"] = [=[Got to say, you're really getting somewhere, boyo, I'm pretty impressed here! And they don't even pay me to do that, I'm just supposed to stand around!]=],
	["0166"] = [=[Heh, hehehe, that's a good one! No! Probably not. Wasn't anything in the old contract about that... huh.]=],
	["0167"] = [=[I am an individual of some integrity, boyo, and protect my sources with my life! You'll have to kill me if you want to make me squeal!]=],
	["0168"] = [=[Let me give you a piece of advice, boyo. You run across a guy like me out there, you just give him a good stab right in the back without a second thought before he sends you crying back to Papa.]=],
	["0169"] = [=[Hey pal watch where you throw those bloodstone things of yours, you drop them, you go pick them up, you understand? But if somebody gives you grief, you got my permission to chuck one right in his eye!]=],
	["0170"] = [=[You're pretty quick, you know, boyo! Just be sure to use that fancy dash of yours and keep 'em guessing! Don't let 'em catch you standing still!]=],
	["0171"] = [=[Little tip, boyo? You find any coinage while you're out there, you be sure to pawn it off to that old Charon, boatman guy? Use it or lose it, pal, use it or lose it.]=],
	["0173"] = [=[You know something, boyo, I think you could do a real number on one of these columns holding up this place, and bring the whole thing down in just a few swipes, boom, boom, BOOM! I'd hate to be standing near one of them if you did!]=],
	["0174"] = [=[Once in a while, pal, you're going to see a real fancy bozo try to ruin your good time. You'll know him 'cause he's glowing like a light, but that's his special armor, see? You got to punch right through it, he's going to shrug you off until you do!]=],
	["0248"] = [=[Boyo, next time you make it to the big VIP area upstairs, you watch out for those weapon-wielding gents out there! The eyeball soul thing that pops out when you beat 'em? You got to squash those, too, or else they'll grab their gear and come right back!]=],
	["0251"] = [=[That's just it! Those weapons of yours, they have seen some real business, pal. You're giving them a real workout, so maybe they're starting to like you or something? Loosening up a bit, you know? Like you and me!]=],
	["0274"] = [=[Pal, I don't know a thing about it, honest! I was just minding my own business, when all the sudden, wham! I get hit right in the back. I fall to pieces, no idea what's going on! When I finally come to, the window job was done...!]=],
	["0277"] = [=[Oh I didn't mean it like a bad thing, boyo! The weirder you make those things, the more it gives me the shakes, and keeps me hopping like this nice and steady till the next time you get back! So, thanks!]=],
	["0308"] = [=[I am. And funny you should put it like that. Boyo, I am asking you to get me out of here. Permanently, if you catch my drift. This standing around stuff... just kind of wears on you, after a while, you know?]=],
	["0309"] = [=[That blade of yours back there. It's got a special power. You got to spruce it all the way up. Your Aspect, not somebody's else's. Then let me have it with that thing... and I'm out of here.]=],
	["0310"] = [=[That blade of yours back there. It's got a special power. Your Aspect, now that it's maxed out. You got to let me have it with that thing... and then I'm out of here.]=],
	["0311"] = [=[I know it's a lot to dump on you, but I got my reasons. I don't exactly have a lot of options, here, so... give it some thought. Till then, we'll act like nothing's changed, all right?]=],
	["0316"] = [=[Hahaha, got you pretty good, again, didn't I, boyo?! I am asking you to get me out of here. Hahahaha! All that stuff about your blade, and your Aspect, I mean, you ate all of it right up! Woo, hoo-hoo!]=],
	["0317"] = [=[Whoa, whoa whoa whoa whoa, whoa! Now come on, boyo, it was just a joke, I figured things could lighten up a little here. Don't need to do anything rash!]=],
	["0318"] = [=[Whaaa, is that a vintage bottle of Ambrosia, pal?! I never even thought I'd get to try a thing like that, I mean, what am I, here? Know what, I want you to have this. To symbolize our friendship, and in case you ever need a hand out there.]=],
	["0319"] = [=[Aww, no way, boyo, you kidding me right now? Why are you even, I... look, I, I just stand around and let you beat me up, you don't have to do this. You don't even know who I am. Who I was.]=],
	["0320?"] = [=[Hope you enjoyed that vintage bottle of Ambrosia last time, Skelly, because I got you another. Here!]=],
	["0368?"] = [=[If you're having a rough time out there, boyo, you just remember something: You're a god, all right?! Way tougher than you think. They give you trouble, you just turn on God Mode, and you let 'em have it for me!]=],
	["0369"] = [=[Yeah, that's right! Not exactly much to do here, case you hadn't noticed recently! Good thing I'm able to stay occupied with intellectual pursuits.]=],
	["0370"] = [=[TrainingMelee]=],
	["0444"] = [=[Ah, you've come to the right place regarding that, there, pal! It's your mean weapons back there that can find the stuff. Once you get all the way through Tartarus with one, that's all the blood you're going to get! For the time being anyhow.]=],
	["0456"] = [=[Relax, boyo, just had a little chat with your old serving platter over there after you left, is all. That thing hits pretty hard! So, then, I say to it, I see you through the eyes of the crimson phoenix... and you want to know what happened after that?]=],
	["0457"] = [=[Over my shoulder! Anyway, what happened next was nothing! Your Aegis kept on bobbing like a dummy. So then I went and said that mumbo jumbo to every other weapon, but nope! Doesn't work at all. So much for your fancy sorcery, huh?]=],
	["0465"] = [=[Nope! Not any of my business, pal, which is to say, I didn't see a thing! And even if I did, it isn't what I'm paid to do! Don't you have someone in your fancy House there paid to keep watch over stuff like that? Ask them!]=],
	["0476"] = [=[I don't know, there's always the invention of writing stuff down? You'll figure something out.]=],
	["0477"] = [=[Wouldn't know a thing about it! Definitely doesn't have anything to do with those Infernal Arms of yours, some of which appear to still be unavailable to you, as I understand?]=],
	["0479"] = [=[No, I'm worried you'll be wasting your time! If you give that stuff away, don't expect to get anything back. Well, not after the first time, anyway. Usually! I'm just saying... don't get your hopes up.]=],
	["0480?"] = [=[Pal, thanks again for that Nectar bottle from before, stuff just goes right through me like you won't believe! Though, I hope you're not going around giving that stuff away to every bozo you know.]=],
	["0481"] = [=[Oh, you know, just kind of zapped right in, like Papa lets us do! Some of us sometimes. Why do you ask?]=],
	["0482"] = [=[Oh, haha! Well, that's a little personal, don't you think, boyo? I... I don't like to talk about it much. So, if I could have a little privacy...?]=],
	["0483"] = [=[What, haha, you going to believe everything that gabby guy tells you, now, boyo? He doesn't know a thing about me!]=],
	["0484"] = [=[No! Nope. Definitely not working for him, closer to a peer relationship. Well, other than the fact that he's a god and I'm just... well, what you see is what you get with me, pal. Hey, you won't tell anyone, will you? I'm just here to help, I swear!]=],
	["0485"] = [=[Sorry, pal, my lips are sealed. How about we change the subject?]=],
	["0486"] = [=[Nope!]=],
	["0487"] = [=[No way.]=],
	["0488"] = [=[I said no!]=],
	["0489"] = [=[Nuh-uh.]=],
	["0490"] = [=[No. Means. No.]=],
	["0491"] = [=[Nice try, pal.]=],
	["0492"] = [=[...Uh... no...?]=],
	["0493"] = [=[No... please, have mercy, boyo...]=],
	["0494"] = [=[Nrrrghh, all right! But you got to promise me something, promise not to let on or tell anybody in your fancy House, all right? Or else I'm done for. I'm serious!]=],
	["0495"] = [=[...It's Charon.]=],
	["0496"] = [=[Yeah. He's rich. He's got connections to guys like me, and I think he's got a horse in this chariot race you've got going on around here with Papa.]=],
	["0497"] = [=[No idea. Maybe he likes you, maybe he's bored.]=],
	["0498"] = [=[Yep! Now, let's pretend like none of this ever happened, so I can stick around, all right? Remember, pal, you promised!]=],
	["0499"] = [=[Boyo, thought we agreed we weren't going to be having conversations on the subject from here on. Spares me having to spill my guts with my sources later.]=],
	["0500?"] = [=[Skelly, did you tell Charon and Hermes about our little conversation from before, about your sources? Because, I didn't tell them, but... they seemed to know.]=],
	["0501"] = [=[Hey, what makes you think this isn't my real name, pal? I'm offended!]=],
	["0502"] = [=[...Well all right... I was once a commander of men. Name of Schelemeus. Captain of the Cretan second fleet, sailing on Athens under King Minos. We were unstoppable... but then one day... one wrong turn... and we sailed straight into the waters of Charybdis.]=],
	["0503"] = [=[I, uh, pfff, hahaha, boyo, you are something else, you know? All that Schelemeus stuff, I could have had you eating out of my hand for days!]=],
	["0504?"] = [=[Skelly, is it really true you don't want to talk about how you got here? Just curious who you used to be. What you were like. Your real name.]=],
	["0505?"] = [=[Skelly... I'm serious. You really won't tell me anything about you? You're just going to leave me to speculate, forever?]=],
	["0525"] = [=[Ah, you know, while I appreciate that, there, boyo... those kind of social spaces, they're not really for me. I kind of like it out here, just me, these bats whizzing around from time to time.... Besides! The old contract makes it pretty clear I got to stay right here.]=],
	["0526?"] = [=[Say, mate? I picked up a painting for our lounge that looked a little like yourself. Reminds me... have you ever even been inside? Should come join us sometime.]=],
	["0527"] = [=[Hey, I know people, pal! We'll just have to leave it at that. Now let's see you break some of these bones, huh?]=],
	["0530?"] = [=[Well, pal? You have come a pretty long way, let me tell you. I think most of the smarts I've picked up, you know by now. And so... if I'm fresh out of tips for you... I guess there's only one thing left to do.]=],
	["0535"] = [=[Never said I made it up, pal! I just knew you weren't going to believe me, I mean, look at me! I look like a captain of the Cretan second fleet to you?]=],
	["0536"] = [=[Well, sounds like somebody's never had to lead like fifty-or-something sailors in a voyage across the sea in a Minoan galley with nothing but the stars to guide 'em! What do you think the captains do, pull the oars?]=],
	["0537"] = [=[What is it with you gods talking behind the backs of all your friends, boyo?]=],
	["0538"] = [=[Don't change the subject!]=],
	["0541"] = [=[Yeah! Once you achieve your goal... my contract's up. You won't need me anymore.]=],
	["0542"] = [=[Probably, but... wait, you're really going to stay?]=],
	["0544"] = [=[Ahh, and thus the pupil trains the master, for a change! I hear you, pal. Your secret's safe with me.]=],
	["0546"] = [=[Ohh, don't you even worry about me, there, pal! I much prefer the solitary life, and besides! When things are good for you, they're good for me. Glad everything worked out.]=],
	["0547"] = [=[Oh! Yeah, now that you mention it, I guess that part of the old contract no longer applies. So, go right ahead! Appreciate you asking, pal.]=],
	["0179"] = [=[Wrong! We're talking something really big, here, pal, you see that thing back there? Trinket. Come on, what are you, scared?]=],
	["0183"] = [=[I just knew you had it in you, pal, enjoying your new prize? Pact of Punishment, Shmact of Punishment, no problem, know what I mean? 'Course, that was just the easy one you got there, pretty sure I could've got that one, myself.]=],
	["0184"] = [=[Look, boyo, there was a little mix-up when we put in the request for that thing, see? I told 'em to make something that'll make me look good with my sources, and anyway that's how it all turned out. The other ones turned out much better, though, you'll see!]=],
	["0188"] = [=[I am offended, pal! You haven't even seen the third one yet, so how can you insinuate a thing like that?! Maybe I was wrong about you. I thought you really were the one!]=],
	["0189"] = [=[How could you--? I would return those statues for a full refund right here and now, if I could move! And if there was a refund policy on them.]=],
	["0193"] = [=[Look I'm sorry I messed up your statues, boyo. Really. When I saw them, I just kind of freaked. But then I figured there's no way he's going to see how they turned out, so, I just rolled with it, you know?]=],
	["0194"] = [=[Oh you better believe it, pal! So how about we call it even. We've been through a lot. Both of us! Really learned from this experience, and now, we share a deeper understanding, yeah?]=],
	["0002"] = [=[Hey boyo watch where you throw those fireballs of yours, cause they wreak a lot of havoc, and I end up having to clean up after, you understand? But if someone gives you grief, you got my permission to chuck one right in his eye!]=],
	["0005"] = [=[Nice place you got up here, boyo! Though enough with the small talk already, let's get on with the sparring practice! Go on, let me have it, give me everything you got!!]=],
	["0007"] = [=[Psst, over here!]=],
	["0008"] = [=[Hey hey!]=],
	["0009"] = [=[Hey boyo!]=],
	["0010"] = [=[Want a piece of me boyo?]=],
	["0011"] = [=[Think you can take me boyo?]=],
	["0012"] = [=[Eh, not bad!]=],
	["0013"] = [=[Felt that one!]=],
	["0014"] = [=[Eh nice!]=],
	["0015"] = [=[Yeah that's it!]=],
	["0016"] = [=[That's the stuff!]=],
	["0017"] = [=[Yeah boyo!]=],
	["0018"] = [=[Yeah!]=],
	["0019"] = [=[Oh yeah!]=],
	["0020"] = [=[Pretty nice!]=],
	["0021"] = [=[Whoa yeah!]=],
	["0022"] = [=[Oww nice!]=],
	["0023"] = [=[Good one!]=],
	["0024"] = [=[Almost felt that!]=],
	["0025"] = [=[Heh!]=],
	["0047"] = [=[What can I do for you?]=],
	["0048"] = [=[What's up, boyo.]=],
	["0049"] = [=[I'm all ears!]=],
	["0050"] = [=[Yeah, what?]=],
	["0051"] = [=[What do you need?]=],
	["0052"] = [=[Can I help you, or what?]=],
	["0053"] = [=[Yeah all right.]=],
	["0054"] = [=[Don't see why not.]=],
	["0055"] = [=[You got it.]=],
	["0056"] = [=[Gotcha.]=],
	["0057"] = [=[No prob.]=],
	["0058"] = [=[Sure!]=],
	["0059"] = [=[Yeah sure.]=],
	["0060"] = [=[I hear that.]=],
	["0061"] = [=[No yeah I got it.]=],
	["0062"] = [=[Leave it to me!]=],
	["0063"] = [=[Whoa-hoh!]=],
	["0064"] = [=[Yeeoww!]=],
	["0065"] = [=[That's the spirit!]=],
	["0066"] = [=[Yeah keep going!]=],
	["0067"] = [=[Ho-hohhh!]=],
	["0068"] = [=[Whoo!]=],
	["0069"] = [=[That kind of hurt!]=],
	["0070"] = [=[Hoh, yeah!]=],
	["0071"] = [=[Nice one!]=],
	["0072"] = [=[Real nice!]=],
	["0073"] = [=[Change of plan there huh?]=],
	["0074"] = [=[Yeah that one's pretty nice.]=],
	["0075"] = [=[Ooh change of plan I like it!]=],
	["0076"] = [=[This ought to be good.]=],
	["0077"] = [=[Want to try that thing out?]=],
	["0078"] = [=[You using that thing now huh?]=],
	["0079"] = [=[Hey that looks pretty mean.]=],
	["0080"] = [=[Ooh would you look at that.]=],
	["0081"] = [=[Pretty mean knife you got there.]=],
	["0082"] = [=[Pretty scary serving platter there.]=],
	["0083"] = [=[That some kind of fishing pole or what?]=],
	["0084"] = [=[Scared to get up close and personal, boyo?]=],
	["0085"] = [=[Heeey nice!]=],
	["0086"] = [=[What'd you get, what'd you get?]=],
	["0087"] = [=[Get anything good?]=],
	["0088"] = [=[What is that thing?]=],
	["0089"] = [=[Hooh, you got one!]=],
	["0090"] = [=[Time for a break there, pal?]=],
	["0091"] = [=[So you want to give it a rest, or what?]=],
	["0092"] = [=[All right, pal, you can stop!]=],
	["0093"] = [=[Anytime you want to stop, there, boyo.]=],
	["0094"] = [=[Well this is awkward!]=],
	["0095"] = [=[How am I supposed to get back?]=],
	["0096"] = [=[Don't think I'm supposed to be here.]=],
	["0097"] = [=[Uh kind of stuck here, pal.]=],
	["0098"] = [=[No, nooooooo!]=],
	["0099"] = [=[Yep that'll do it...!]=],
	["0100"] = [=[Yeaaaah!]=],
	["0101"] = [=[Sweet release!]=],
	["0102"] = [=[AAAAAAAHH!!]=],
	["0103"] = [=[Ooh be right back...!]=],
	["0104"] = [=[Oops got to go!]=],
	["0105"] = [=[Ahhhhh...]=],
	["0106"] = [=[Hah, haha, bet I got you pretty good!]=],
	["0107"] = [=[What'd I miss?]=],
	["0108"] = [=[Hahah, bet I got you pretty good!]=],
	["0109"] = [=[Aand, we're back.]=],
	["0110"] = [=[All right back to work.]=],
	["0111"] = [=[Miss me, boyo?]=],
	["0112"] = [=[Heeey.]=],
	["0113"] = [=[Oh hi.]=],
	["0114"] = [=[All right I'm back!]=],
	["0121"] = [=[Haw, just what I always wanted, there, besides getting smacked around for no good reason! I'll take that off your hands, all right, but let me give you this!]=],
	["0122"] = [=['Bout time you showed up!]=],
	["0123"] = [=[They always come back.]=],
	["0124"] = [=[Been waiting over here!]=],
	["0125"] = [=[Right on schedule!]=],
	["0126"] = [=[Hey!]=],
	["0127"] = [=[Been here the whole time!]=],
	["0128"] = [=[Haven't moved a muscle!]=],
	["0129"] = [=[Ready to go or what?]=],
	["0130"] = [=[Want to fight?]=],
	["0131"] = [=[Heh-heyy!]=],
	["0132"] = [=[How's it going?]=],
	["0133"] = [=[There he is!]=],
	["0134"] = [=[Oh hey.]=],
	["0135"] = [=[What's the good word?]=],
	["0136"] = [=[Any luck last time?]=],
	["0137"] = [=[Looking good!]=],
	["0138"] = [=[Ah you shot me!]=],
	["0139"] = [=[I'll hang onto that!]=],
	["0140"] = [=[Caught it!]=],
	["0141"] = [=[Stuck me good!]=],
	["0142"] = [=[I'm hit!]=],
	["0143"] = [=[Here you go!]=],
	["0144"] = [=[Take another shot?]=],
	["0145"] = [=[Back to you!]=],
	["0146"] = [=[Catch!]=],
	["0147"] = [=[Dropped something!]=],
	["0148"] = [=[Who's this handsome fellow?]=],
	["0149"] = [=[Hey who's your friend?]=],
	["0150"] = [=[Hey I know that guy.]=],
	["0151"] = [=[Look at this guy over here.]=],
	["0152"] = [=[Hey how's it going?]=],
	["0153"] = [=[Oh hey Ron.]=],
	["0154"] = [=[Oh hey guys.]=],
	["0155"] = [=[Hey boyo, hey Ron.]=],
	["0156"] = [=[Hey think there's something for you over there.]=],
	["0157"] = [=[Something you ought to check out over there.]=],
	["0158"] = [=[Delivery or something over there.]=],
	["0163"] = [=[...I mean, Achilles, pal, look I don't want to bust your chops or anything, but all I'm saying here, is, personally? I never took a shot to the ankle or whatever, back when I was alive!]=],
	["0164"] = [=[Hoh, I was something else, all right, you should have seen me! I could take anybody on the isle, blindfolded!]=],
	["0172"] = [=[<Ah! Oof! Augh! Ungh. Waw! Brlrl! Bwuh! Ungh! Woo!>]=],
	["0175"] = [=[Good, just the boyo I wanted to see, c'mere!]=],
	["0176"] = [=[Oh, have I got something for you, boyo!]=],
	["0177"] = [=[Get a load of them prizes over there.]=],
	["0180"] = [=[Hah you did it, boyo! Reward's right over there!]=],
	["0181"] = [=[Hooray, you did it, pal!]=],
	["0182"] = [=[She sure is! Isn't she beautiful!]=],
	["0185"] = [=[Whoa-hoh you earned yourself another one, congrats!]=],
	["0186"] = [=[Well I'll be a hellhound's hindquarters, you really pulled it off.]=],
	["0187"] = [=[Because, pal, you are a discerning individual!]=],
	["0190"] = [=[Oh no...]=],
	["0191"] = [=[Yes, pal. Yes she is.]=],
	["0192"] = [=[...What... you really mean that, pal?]=],
	["0195"] = [=[I'll say!]=],
	["0196"] = [=[Isn't it, though?]=],
	["0197"] = [=[And have I mentioned that it cost a lot of coin?]=],
	["0198"] = [=[It weighs an awful lot, too.]=],
	["0199"] = [=[I know what you mean pal.]=],
	["0200"] = [=[Definitely yeah.]=],
	["0201"] = [=[You said it, boyo.]=],
	["0202"] = [=[Isn't she beautiful?]=],
	["0203"] = [=[I was just thinking the same.]=],
	["0204"] = [=[You got taste, pal, I will give you that.]=],
	["0205"] = [=[She's definitely pretty good!]=],
	["0206"] = [=[Only the best for you, pal.]=],
	["0207"] = [=[That is an excellent interpretation boyo.]=],
	["0208"] = [=[I see exactly what you mean.]=],
	["0209"] = [=[I knew you would appreciate that aspect.]=],
	["0210"] = [=[I know, right?]=],
	["0211"] = [=[Oh absolutely, yeah.]=],
	["0212"] = [=[Whoa don't you touch that thing!]=],
	["0213"] = [=[That is a priceless work of art there pal!]=],
	["0214"] = [=[Hey, don't you scratch that thing, boyo!]=],
	["0215"] = [=[You're killing me pal.]=],
	["0216"] = [=[No, not the statue, please!]=],
	["0217"] = [=[Don't do it!]=],
	["0218"] = [=[No, stop!]=],
	["0219"] = [=[Please pal.]=],
	["0220"] = [=[Aw you are cruel.]=],
	["0221"] = [=[Hey watch the statues!]=],
	["0222"] = [=[Whoa whoa whoa!]=],
	["0223"] = [=[Hey watch it!]=],
	["0224"] = [=[Don't hit those!]=],
	["0225"] = [=[Whoa careful pal!]=],
	["0226"] = [=[Hey stop it!]=],
	["0227"] = [=[Go fill out that form you got.]=],
	["0228"] = [=[I don't make the rules, pal.]=],
	["0229"] = [=[Got to sign up for this contest.]=],
	["0230"] = [=[Go on, I dare you!]=],
	["0231"] = [=[Do you have the guts?]=],
	["0232"] = [=[Go on...]=],
	["0233"] = [=[Uh-uh-uh!]=],
	["0234"] = [=[Gotta earn it, pal!]=],
	["0235"] = [=[Think you got what it takes?!]=],
	["0236"] = [=[It's an amazing prize, boyo!]=],
	["0237"] = [=[Come on, pal, live a little!]=],
	["0238"] = [=[Nuh-uh, you gotta work for it!]=],
	["0239"] = [=[Huzzah!]=],
	["0240"] = [=[We have a winner!]=],
	["0241"] = [=[You earned it, pal.]=],
	["0242"] = [=[Ta-daaaa!]=],
	["0243"] = [=[Special delivery for you back there, boyo!]=],
	["0244"] = [=[Keep your finger on the trigger at all times, pal.]=],
	["0245"] = [=[Nothing to it, pal, just point and shoot.]=],
	["0246"] = [=[Know how to use that thing?]=],
	["0247"] = [=[You got a license for that thing?]=],
	["0249"] = [=[Might want to check your stash of weapons over there...]=],
	["0252"] = [=[Hey what just happened?]=],
	["0253"] = [=[Whoa what was that?]=],
	["0254"] = [=[Hey what's going on back there?]=],
	["0255"] = [=[What's all the racket over there?]=],
	["0256"] = [=[Hey whoa what?]=],
	["0257"] = [=[What did you do, boyo?]=],
	["0258"] = [=[Whoa can I see?]=],
	["0259"] = [=[What did you just do?]=],
	["0260"] = [=[You all right back there pal?]=],
	["0261"] = [=[What kind of sorcery was that?]=],
	["0262"] = [=[Never felt a cut like that before!]=],
	["0263"] = [=[Love what you've done to your sword!]=],
	["0264"] = [=[That bow's got a different sting to it!]=],
	["0265"] = [=[New arrows or something there pal?]=],
	["0266"] = [=[Your shield's looking pretty handsome pal!]=],
	["0267"] = [=[I get the feeling I am being watched...?]=],
	["0268"] = [=[Never been stabbed quite like that!]=],
	["0269"] = [=[Felt all three points on that spear, pal!]=],
	["0270"] = [=[Hey that shot felt different somehow!]=],
	["0271"] = [=[You been messing with that shooty thing pal?]=],
	["0272"] = [=[Uh, might want to see this, boyo, over to my left?]=],
	["0273"] = [=[Look what they did to your pink window, pal!!]=],
	["0275"] = [=[Hey, the Pact lit up, you must have done something!]=],
	["0278"] = [=[Forget something, or what?]=],
	["0279"] = [=[What's the matter there boyo?]=],
	["0280"] = [=[Said our good-byes already pal.]=],
	["0281"] = [=[What you need more practice, pal?]=],
	["0282"] = [=[Just go, pal. You can do it.]=],
	["0283"] = [=[Go on, boyo, get out of here.]=],
	["0284"] = [=[Don't stick around on my account, boyo.]=],
	["0285"] = [=[Need another fancy weapon there or what?]=],
	["0286"] = [=[What do you need there pal?]=],
	["0287"] = [=[Not ready yet or something?]=],
	["0288"] = [=[Rolling with that thing, eh?]=],
	["0289"] = [=[Care for a warm-up with that?]=],
	["0290"] = [=[That would've been my pick.]=],
	["0291"] = [=[Bet you couldn't hit me with that, pal.]=],
	["0292"] = [=[That one huh...]=],
	["0293"] = [=[Time to give that thing some work I guess.]=],
	["0294"] = [=[You be careful with that one boyo.]=],
	["0295"] = [=[I got your chopping block right here, pal.]=],
	["0296"] = [=[Up for some slicing huh.]=],
	["0297"] = [=[Stick it to me, boyo, come on!]=],
	["0298"] = [=[Just watch the ribs with that, OK?]=],
	["0299"] = [=[Go on and clock me with that if you want.]=],
	["0300"] = [=[I still don't get what that's supposed to be.]=],
	["0301"] = [=[Give me one of them arrows right in the eye!]=],
	["0302"] = [=[Couple of practice shots or something?]=],
	["0303"] = [=[Go on, boyo, shoot me, let's see you do it!]=],
	["0304"] = [=[How about you give me your best shot!]=],
	["0305"] = [=[Bet you can't hit me repeatedly from there.]=],
	["0306"] = [=[Hey, pal, uh, wanted to talk to you...]=],
	["0312"] = [=[That's it... the blade... you got to let me have it with that thing.]=],
	["0313"] = [=[That's it, keep going!!]=],
	["0314"] = [=[I'm... finally... free... boyo...]=],
	["0315"] = [=[AH, hahahaha, whoo-hoo-hoo!]=],
	["0320"] = [=[Hah!! Nope!]=],
	["0321"] = [=[What's all this riff-raff?]=],
	["0322"] = [=[Come on, bozo, pick on someone your own size!]=],
	["0323"] = [=[These bozos causing problems, pal?]=],
	["0324"] = [=[Nobody messes with my pal!]=],
	["0325"] = [=[Hey how's everybody doing?]=],
	["0326"] = [=[Waaaaaaaa I'm an important target!!]=],
	["0327"] = [=[Whoever kills me gets a big promotion!]=],
	["0328"] = [=[Ah boyo this place is a mess!]=],
	["0329"] = [=[Whoa nice place to stand around!]=],
	["0330"] = [=[Got here just as soon as I was able, pal!]=],
	["0331"] = [=[I shall protect you, pal!]=],
	["0332"] = [=[Hah what a bunch of bozos!!]=],
	["0333"] = [=[Look at all these guys, come on!]=],
	["0334"] = [=[Heeey bozo, let's see what you got!]=],
	["0335"] = [=[What'd I miss, anything good?]=],
	["0336"] = [=[It's standing doing nothing time!]=],
	["0337"] = [=[You bozos look like you could use some practice!]=],
	["0338"] = [=[You mess with my pal, you mess with me!]=],
	["0339"] = [=[I'll hold them off, boyo, you do your thing!]=],
	["0340"] = [=[Forget about me, boyo! Save yourself!]=],
	["0341"] = [=[Oh I got your back, there, pal!]=],
	["0342"] = [=[Ah dang it!]=],
	["0343"] = [=[Ah dang!]=],
	["0344"] = [=[Aack!]=],
	["0345"] = [=[Whaa?]=],
	["0346"] = [=[Blarrgh!]=],
	["0347"] = [=[I'm done for!]=],
	["0348"] = [=[I'm out!]=],
	["0349"] = [=[Uh, pal?!]=],
	["0350"] = [=[Well this is awkward.]=],
	["0351"] = [=[Hey, nice.]=],
	["0352"] = [=[You did it!]=],
	["0353"] = [=[Nice work there pal.]=],
	["0354"] = [=[Well my work here is done.]=],
	["0355"] = [=[You showed them, pal!]=],
	["0356"] = [=[Well that's a wrap.]=],
	["0357"] = [=[Done and done!]=],
	["0358"] = [=[Well see you!]=],
	["0359"] = [=[Well better go!]=],
	["0360"] = [=[Hey, hey, what's going on?]=],
	["0361"] = [=[Look at the size of that thing!]=],
	["0362"] = [=[Hey toughguy, over here!]=],
	["0363"] = [=[Wha, is that Theseus?!]=],
	["0364"] = [=[Hey Thanatos, big fan right here!]=],
	["0365"] = [=[Uh, hey, uh... hey!]=],
	["0366"] = [=[Need my services again, boyo?]=],
	["0368"] = [=[Exactly, pal, that's it!]=],
	["0372"] = [=[Somebody messing with you, boyo?!]=],
	["0373"] = [=[You need a skeleton to stand around?]=],
	["0374"] = [=[Be there in just a second or two, pal!]=],
	["0375"] = [=[I shall answer the call, boyo!]=],
	["0376"] = [=[I hear you, pal, hang on!]=],
	["0377"] = [=[You called, boyo?]=],
	["0378"] = [=[Hey hey, what's going on?]=],
	["0379"] = [=[Thank you for calling pal!]=],
	["0380"] = [=[It's time to get beat up!]=],
	["0381"] = [=[Don't need to tell me twice!]=],
	["0382"] = [=[I'm back, what did I miss?]=],
	["0383"] = [=[Need something else from me?]=],
	["0384"] = [=[Oh I will be right back!]=],
	["0385"] = [=[Be back in just a sec!]=],
	["0386"] = [=[You called again, boyo?]=],
	["0387"] = [=[Whoa it is hot in here!]=],
	["0388"] = [=[Hey look at all that magma!]=],
	["0389"] = [=[This place is pretty nice!]=],
	["0390"] = [=[Whoa, look at all of this!]=],
	["0391"] = [=[Hey real fancy place!]=],
	["0392"] = [=[Whoa this place is a dump!]=],
	["0393"] = [=[The air feels weird up here!]=],
	["0394"] = [=[Your mama presses olive oil!]=],
	["0395"] = [=[Hey pick on somebody my size!]=],
	["0396"] = [=[Think you can break these bones?]=],
	["0397"] = [=[Nyah-nyah come get me!]=],
	["0398"] = [=[Nyah, come get me and all that!]=],
	["0399"] = [=[Hope I don't die and drop this precious loot!]=],
	["0400"] = [=[You don't have what it takes!!]=],
	["0401"] = [=[Hey, may I have your attention for a sec?]=],
	["0402"] = [=[Don't mean to interrupt!!]=],
	["0403"] = [=[Come on, you bozos, do it!]=],
	["0404"] = [=[I'm here, kill me, you bozos!]=],
	["0405"] = [=[Come on, kill me, you goofs!]=],
	["0406"] = [=[Come on! Get me already!]=],
	["0407"] = [=[Come on, kill me!]=],
	["0408"] = [=[Come on, kill me, I'm here!!]=],
	["0409"] = [=[Kill me, I'm here!]=],
	["0410"] = [=[Come on, do it, kill me!!]=],
	["0411"] = [=[What's the matter, scared?!]=],
	["0412"] = [=[You want a piece of me you guys?!]=],
	["0413"] = [=[Come on, you bozos, let's see what you got!]=],
	["0414"] = [=[Hey bozos, over here!]=],
	["0415"] = [=[Got some real fancy bozos over here!]=],
	["0416"] = [=[These guys don't look so tough!]=],
	["0417"] = [=[Oh I can take a hit!!]=],
	["0418"] = [=[Come give me your best shot!!]=],
	["0419"] = [=[You won't take me alive!!]=],
	["0420"] = [=[Hah!]=],
	["0421"] = [=[Yeah that's it!]=],
	["0422"] = [=[What if I beg for mercy, huh?]=],
	["0423"] = [=[Ah, no, keep hitting me!]=],
	["0424"] = [=[The pain is indescribable!]=],
	["0425"] = [=[Didn't hurt.]=],
	["0426"] = [=[Didn't hurt!!]=],
	["0427"] = [=[Felt nothing there sorry!]=],
	["0428"] = [=[Weak!!]=],
	["0429"] = [=[Nah that was nothing.]=],
	["0430"] = [=[Pssh I could hit harder than that!]=],
	["0431"] = [=[You call that a hit?]=],
	["0432"] = [=[Oh please.]=],
	["0433"] = [=[Nope couldn't feel a thing!]=],
	["0434"] = [=[Dang got to go!]=],
	["0435"] = [=[I can't hold out boyo!]=],
	["0436"] = [=[Avenge me, pal!!]=],
	["0437"] = [=[You got this, boyo, go...!]=],
	["0438"] = [=[You bozos going to pay!]=],
	["0439"] = [=[I swear I'll be avenged!!]=],
	["0440"] = [=[You haven't seen the last of me!!]=],
	["0441"] = [=[Ack, lucky shot!]=],
	["0442"] = [=[Oof all right I'm out!]=],
	["0443"] = [=[Hey go check on your pointy spear boyo!]=],
	["0446"] = [=[Whoa what in the world is that?]=],
	["0447"] = [=[More of a slicing feel there rather than a stabbing!]=],
	["0448"] = [=[Well see you.]=],
	["0449"] = [=[I'll just hang out a while.]=],
	["0450"] = [=[So long pal!]=],
	["0451"] = [=[Bye boyo.]=],
	["0452"] = [=[Glad to be of service!]=],
	["0453"] = [=[So, uh... that happened.]=],
	["0454"] = [=[I, uh... I'll just be over here.]=],
	["0459"] = [=[Whoa, those are some paws!]=],
	["0460"] = [=[What, you going to sock it to me, pal?]=],
	["0461"] = [=[You like those mittens huh?]=],
	["0458"] = [=[Hey, uh, something back there for you, pal!]=],
	["0462"] = [=[Yeah, give me your best shot!]=],
	["0463"] = [=[Yeah, put up your dukes!]=],
	["0464"] = [=[Sock it to me, boyo!]=],
	["0466"] = [=[Whoaa that's a nifty sword!]=],
	["0467"] = [=[Hoh now that's a shiny bow you got right there!]=],
	["0468"] = [=[Yeoow that's got a nice little kick of heat to it!]=],
	["0469"] = [=[Hooh now that's what I call getting shot by arrows!]=],
	["0470"] = [=[Your serving platter, what did you just do?]=],
	["0471"] = [=[Ah, yeah, that's the stuff!]=],
	["0472"] = [=[Uh that's no shooty thing I recognize.]=],
	["0473"] = [=[Ooh, nice burning sensation from that!]=],
	["0480"] = [=[Hahaha, sure!]=],
	["0500"] = [=[If you did, pal, I would not be here right now!]=],
	["0504"] = [=[Oh, hahaha, but I do!]=],
	["0505"] = [=[Yep!]=],
	["0506"] = [=[Heya.]=],
	["0507"] = [=[Hey, pal.]=],
	["0508"] = [=[Boyo.]=],
	["0509"] = [=[Boyo!]=],
	["0510"] = [=[Hey.]=],
	["0511"] = [=[There you are.]=],
	["0512"] = [=[I knew it.]=],
	["0513"] = [=[Back, huh.]=],
	["0514"] = [=[Need some practicing?]=],
	["0515"] = [=[Finally!]=],
	["0526"] = [=[Yeah, no, that definitely wouldn't fly.]=],
	["0530"] = [=[Yep. Now hop to it!]=],
	["0531"] = [=[I feel exactly the same way.]=],
	["0532"] = [=[Can't get over how tall they are!]=],
	["0533"] = [=[That is one keen eye.]=],
	["0534"] = [=[I can't get over it, myself.]=],
	["0539"] = [=[Hahaha.]=],
	["0548"] = [=[Oof, I felt that deep down in my jaw!]=],
	["0549"] = [=[Hey who turned out the lights?!]=],
	["0550"] = [=[Hey, hey, what's going on?]=],
	["0551"] = [=[Heya lady!]=],
	["0552"] = [=[You keep that whip away from my pal!]=],
	["0553"] = [=[So, what's going on between you two?]=],
	["0554"] = [=[Hey you big lug, over here!]=],
	["0555"] = [=[Hey Big-Bones, want some of this?!]=],
	["0556"] = [=[Why'd you drag me into this one, pal?!]=],
	["0557"] = [=[Nice bone structure on that thing over there!]=],
	["0558"] = [=[Hey, bull boy, what's the matter?]=],
	["0559"] = [=[Ooh, help, he's got a double bladed axe!]=],
	["0560"] = [=[Charge into this, bull boy!]=],
	["0561"] = [=[Remember me, bull boy?!]=],
	["0562"] = [=[The king of Athens, I'm so scared, boyo!]=],
	["0563"] = [=[And the crowd goes nuts!]=],
	["0564"] = [=[This one's for you guys out in the cheap seats!]=],
	["0565"] = [=[Looks like I made it for the big event!]=],
	["0566"] = [=[Hey Thanatos, big fan right here!]=],
	["0567"] = [=[Whoa hey, it's Thanatos!]=],
	["0568"] = [=[Ooh it's that Thanatos!]=],
	["0569"] = [=[Don't kill me, Thanatos!]=],
	["0570"] = [=[Uh, must have taken a wrong turn somewhere!]=],
	["0571"] = [=[Hey, what you doing all the way up here?]=],
	["0572"] = [=[Whoa it's Papa, you're in trouble, pal!]=],
	["0573"] = [=[Think this one's between you and Papa, pal!]=],
	["0574"] = [=[You beat me, I'll just keep coming back!]=],
	["0575"] = [=[Go on and sock it to me, here!]=],
	["0576"] = [=[Can't even kill an unarmed skeleton!]=],
	["0577"] = [=[How about a stationary target for a change?]=],
	["0578"] = [=[Want me to move, make me!]=],
	["0579"] = [=[Come give me your best shot!]=],
	["0580"] = [=[Oh, help me, boyo, I'm so scared!]=],
	["0581"] = [=[Ahahaha, please!]=],
	["0582"] = [=[Woo, hoohoohoohoo!]=],
	["0583"] = [=[You know who you're dealing with?]=],
	["0584"] = [=[Eugh, what happened to your mitts, boyo?]=],
	["0585"] = [=[Can't see nothing over here!]=],
	["0586"] = [=[Hey, what the?]=],
	["0587"] = [=[Ah, this again huh.]=],
	["0588"] = [=[I'm scared, hold me, boyo!]=],
	["0589"] = [=[Where'd everybody go?]=],
	["0590"] = [=[Aaaah!]=],
	["0591"] = [=[Ah, no, not this again!]=],
	["0592"] = [=[Ah! I am slain...!]=],
	["0593"] = [=[Niiiice....]=],
	["0594"] = [=[Aand, I'm dead.]=],
	["0595"] = [=[Farewell... boyo...]=],
	["0596"] = [=[Ah, my femur!]=],
	["0597"] = [=[Right in the vertebrae!]=],
	["0598"] = [=[Right in the cranium!]=],
	["0599"] = [=[Right in the pelvis, oof!]=],
	["0600"] = [=[I'm... too young... to die...]=],
	["0601"] = [=[I don't want to die!]=],
	["0602"] = [=[Anyways...]=],
	["0603"] = [=[Back in one piece!]=],
	["0604"] = [=[Good as new!]=],
	["0605"] = [=[Never felt so alive!]=],
	["0606"] = [=[Go again?]=],
	["0607"] = [=[I live again, boyo!]=],
	["0608"] = [=[<Gasp> I'm alive!!]=],
	["0609"] = [=[All that damage, that was nothing, pal!]=],
}
